:USER_GUID: %GUID%
:USERNAME: %USERNAME%
:markup-in-source: verbatim,attributes,quotes
:show_solution: true

[discrete]
== Presented By

  * Christoph Doerbeck
  * Karl Abbott
  * Eddie Chen
  * Gordon Keegan
  * Matt St. Onge

== Overview

First of all, THANK YOU for registering and participating in *The Definitive Red Hat Enterprise Linux 8 Hands-on Lab*.  The lab team has worked very
 hard to assemble a series of exercises to introduce many of the new features and capabilities found in the next great release of RHEL.  We hope you
 enjoy this experience and please don't hesitate to ask questions.

This hands-on lab will lead you through a mix of self-paced and proctored exercises covering core and updated capabilities of Red Hat Enterprise Lin
ux 8. Led by your favorite Red Hat field solution architects, key areas covered include:

  * Ease of use: web console, application-streams, stratis, systemd

  * Security: Simple system-level disk encryption, session recording with tlog, net-filter and nft-tools

  * Performance: Tracing with ebpf, Data Optimization with lvm and vdo

  * Management: Virtual machines with libvirt and Image Builder, Containers with podman, buildah and skopeo, boot image management with boom.

And plenty more... There will be ample experts on hand to help and answer your questions. Join us and begin your journey to becoming a Red Hat Enter
prise Linux 8 expert.

Also, please don't forget to review this session at the completion of this lab.  Your reviews and feedback help keep labs like these as top attracti
ons for the Red Hat Summit.

NOTE:  This whole effort is done using official Red Hat software and although things can likely be set up to work with upstream software components
(Fedora, CentOS, etc...), alternate derivatives of RHEL are not tested or validated with these exercises.

Source for this workshop: http://github.com/xtophd/RHEL8-Workshop
