:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Workshop Abstract

This hands-on lab will lead you through a mix of self-paced and proctored exercises covering core and updated 
capabilities of Red Hat Enterprise Linux 8.  Led by your favorite Red Hat field solution architects, key areas covered include:

    * Ease of use: web console, yum 4, application-streams
    * Security: Simple system-level disk encryption, session recording with tlog, net-filter and nft-tools
    * Performance: Tracing with ebpf, Cgroups v1 vs. v2, XFS enhancements
    * Management: Gold image creation with image builder, Containers with podman, skopio, buildah, boot image management with Boom.

And plenty more... There will be ample experts on hand to help and answer your questions. Join us and begin your journey to 
becoming a Red Hat Enterprise Linux 8 expert.

[discrete]
== End of Unit

link:../RHEL8-Workshop.adoc[Return to Document]

////
Always end files with a blank line to avoid include problems.
////
