:sectnums:
:sectnumlevels: 3
:markup-in-source: verbatim,attributes,quotes
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


:toc:
:toclevels: 1

= Application Streams

== Overview

== Getting Started

For these exercises, you will be using the host `node1` as user `root`.

From host `workstation`, ssh to `node1`.

[bash,options="nowrap",subs="{markup-in-source}"]
----
$ *ssh node1*
----

Use `sudo` to elevate your priviledges.

[bash,options="nowrap",subs="{markup-in-source}"]
----
$ *sudo -i*
----

Verify that you are on the right host for these exercises.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *cheat-appstream-checkhost.sh*
----

You are now ready to proceed with these exercises.

== Choosing an appstream module on RHEL 8.

Determine what modules are available.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *yum module list | grep postgresql*

postgresql           9.6         client, server [d]                       PostgreSQL server and client module
postgresql           10 [d]      client, server [d]                       PostgreSQL server and client module
postgresql           12          client, server                           PostgreSQL server and client module
----

This means that I can pick either the postgresql 10 stream (the default), the 9.6 stream, or the 12 stream. This enables me to use whichever postgresql best fits my needs. In the future as new postgresql versions come out, they
can be added as different streams that I can change to as well.
Switching streams is not supported. App Stream allows us to be more in
control with userspace than any previous version of RHEL.

On your new RHEL 8 system, if you do:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *yum install -y postgresql-server*

...<SNIP>...
  Installing       : postgresql-server-10.6-1.module+el8+2469+5ecd5aae.x86_64            3/3
  Running scriptlet: postgresql-server-10.6-1.module+el8+2469+5ecd5aae.x86_64            3/3
  Verifying        : libpq-12.1-3.el8.x86_64                                             1/3
  Verifying        : postgresql-10.6-1.module+el8+2469+5ecd5aae.x86_64                   2/3
  Verifying        : postgresql-server-10.6-1.module+el8+2469+5ecd5aae.x86_64            3/3

Installed:
  postgresql-server-10.6-1.module+el8+2469+5ecd5aae.x86_64      libpq-12.1-3.el8.x86_64
  postgresql-10.6-1.module+el8+2469+5ecd5aae.x86_64

Complete!
----

But let’s say that our application teams have a dependency on 9.6 but we
want to move to RHEL 8. With the app stream, we can do this. Let's do this next exercise on node3. 

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *exit*
----

Then:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *ssh node3*
----

On node3, let’s now run:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *yum module install -y postgresql:9.6/server*
----

The above command tells yum to install the server profile for postgresql
in the 9.6 version.

Once we’ve installed that, we will see:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *yum module list | grep postgresql*

postgresql           9.6 [e]      client, server [d] [i]                   PostgreSQL server and client module
postgresql           10 [d]       client, server [d]                       PostgreSQL server and client module
postgresql           12           client, server                           PostgreSQL server and client module     
----

The [e] by 9.6 means enabled. The [i] by server means installed.
Anywhere that we see a [d] it represents the default on the operating
system.

The server profile installs both the server and the client. If we just
wanted the client, we could remove the server profile:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *yum module remove -y postgresql:9.6/server*
----

and install only the client:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *yum module install -y postgresql:9.6/client*
----

Now let's inspect what yum tells us about the postgresql modules:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *yum module list | grep postgresql*
----

.Command Output
[source,indent=4]
----
postgresql           9.6 [e]      client [i], server [d]                   PostgreSQL server and client module                                         
postgresql           10 [d]       client, server [d]                       PostgreSQL server and client module                                         
postgresql           12           client, server                           PostgreSQL server and client module     
----

This shows us that the 9.6 stream is enabled and the client is installed, but the server is not. If the server were installed, it too would have a [i] in the output.

== Disabling application streams

Another interesting feature of application streams is the ability to
easily prevent packages from being installed. On node3.example.com, we
just installed postgresql. We don’t want to have another database on the
same machine and we see app stream profiles for mysql and mariadb. Let’s
disable these:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *yum module disable mariadb mysql -y*
----

Now when we do yum module list, we will see:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *yum module list | grep -e mariadb -e mysql*

mariadb                  10.3 [d][x]     client, server [d], galera                   MariaDB Module
mysql                    8.0 [d][x]      client, server [d]                           MySQL Module
----

The [x] stands for disabled. When we run:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *yum install mariadb -y*

No match for argument: mariadb
Error: Unable to find a match
----

To re-enable these app streams and allow the packages to be installed,
the command is:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *yum module enable mariadb mysql -y*
----

You may now switch back to the workstation:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *exit*
----

== Ansible automation with App Stream

App Stream operations can be performed in ansible with the dnf module,
like such:


[source,options="nowrap",subs="{markup-in-source}"]
----
- name: install the postgresql 9.6 stream with the client profile.
  dnf:
    name: '@postgresql:9.6/client'
    state: present
----

On the workstation, as root, run:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *cd ~/RHEL8-Workshop*
----

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *ansible-playbook -i config/rhel8-workshop playbooks/appstream-pgsql.yml*
----

then:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *ansible-playbook -i config/rhel8-workshop -o -a "rpm -q postgresql-server"*
----

You should have postgresql-server 10.6 on node1 and 9.6 on node3 and no
postgresql-server on node2.

and:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *ansible rhel8 -o -a "rpm -q postgresql"*
----

You should have postgresql 10.6 on nodes 1 and 2 and postgresql 9.6 on
node3.

== Additional Resources

Red Hat Documentation

    * link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_managing_and_removing_user-space_components/index[RHEL 8 Documentation: Installing, Managing, and Removing User Space Components]
    

[discrete]
== End of Unit

////
Always end files with a blank line to avoid include problems.
////
