:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Application Streams

== Choosing an appstream module on RHEL 8.

Let’s do this on node1.example.com:

.[root@node1]#
----
yum module list
----

We see that we have:

[source,indent=4]
----
postgresql           10 [d]      client, server [d]          PostgreSQL server and client module
postgresql           9.6         client, server [d]          PostgreSQL server and client module
----

This means that I can pick either the postgresql 10 stream (the default)
or the 9.6 stream. This enable me to use an older postgresql than what
RHEL 8 ships. In the future as new postgresql versions come out, they
can be added as different streams that I can change to as well.
Switching streams is not supported. App Stream allows us to be more in
control with userspace than any previous version of RHEL.

On a new RHEL 8 system, if you do:

.[root@node1]#
----
yum install postgresql-server
----

you will get:

[source,indent=4]
----
10.6-1.module+el8+2469+5ecd5aae
----

But let’s say that our application teams have a dependency on 9.6 but we
want to move to RHEL 8. With the app stream, we can do this. On
node3.example.com, let’s run:

.[root@node1]#
----
yum module install postgresql:9.6/server -y
----

The above command tells yum to install the server profile for postgresql
in the 9.6 version.

Once we’ve installed that, if we look at the corresponding section of
yum module list again, we will see:

[source,indent=4]
----
postgresql               10 [d]          client, server [d]                           PostgreSQL server and client module
postgresql               9.6 [e]         client, server [d] [i]                       PostgreSQL server and client module
----

The [e] by 9.6 means enabled. The [i] by server means installed.
Anywhere that we see a [d] it represents the default on the operating
system.

The server profile installs both the server and the client. If we just
wanted the client, we could remove the server profile:

.[root@node1]#
----
yum module remove postgresql:9.6/server -y
----

and install only the client:

.[root@node1]#
----
yum module install postgresql:9.6/client -y
----

We would then see (in yum module list):

[source,indent=4]
----
postgresql               10 [d]          client, server [d]                           PostgreSQL server and client module
postgresql               9.6 [e]         client [i], server [d]                       PostgreSQL server and client module
----

== Disabling application streams

Another interesting feature of application streams is the ability to
easily prevent packages from being installed. On node3.example.com, we
just installed postgresql. We don’t want to have another database on the
same machine and we see app stream profiles for mysql and mariadb. Let’s
disable these:

.[root@node1]#
----
yum module disable mariadb mysql -y
----

Now when we do yum module list, we will see:

[source,indent=4]
----
mariadb                  10.3 [d][x]     client, server [d], galera                   MariaDB Module
mysql                    8.0 [d][x]      client, server [d]                           MySQL Module
----

The [x] stands for disabled. When we run:

.[root@node1]#
----
yum install mariadb -y
----

we get:

[source,indent=4]
----
No match for argument: mariadb
Error: Unable to find a match
----

To re-enable these app streams and allow the packages to be installed,
the command is:

.[root@node1]#
----
yum module enable mariadb mysql -y
----

Ansible automation with App Stream
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

App Stream operations can be performed in ansible with the dnf module,
like such:

[source,yaml]
----
- name: install the postgresql 9.6 stream with the client profile.
  dnf:
    name: '@postgresql:9.6/client'
    state: present
----

On the workstation, as root, run:

.[root@node1]#
----
ansible-playbook appstream-pgsql.yml
----

then:

.[root@node1]#
----
ansible rhel8 -a "rpm -q postgresql-server"
----

You should have postgresql-server 10.6 on node1 and 9.6 on node3 and no
postgresql-server on node2.

and:

.[root@node1]#
----
ansible rhel8 -a "rpm -q postgresql"
----

You should have postgresql 10.6 on nodes 1 and 2 and postgresql 9.6 on
node3.


== Apendix

Please note that this activity was required with the RHEL 8 BETA we used to constuct this lab.  It has already been executed on the host core.example.com.  This is provided as reference only.

=== Rebuilding repositories that have AppStream components

==== Unpack the RHEL 8 DVD

This presumes the DVD is mounted on /mnt

.[root@node1]#
----
mkdir /var/www/html/repos/rhel8
cd /var/www/html/repos/rhel8
tar cf - -C /mnt . | tar xvf -
----

Install the required tools to create the repo with functional application streams

.[root@node1]#
----
yum install createrepo_c
cd /var/www/html/repos/rhel8/AppStream
cd repodata
gunzip 87ada5e5d9c759dccdff8955fc93c33760454907021411ef552d3a6a8ca5ecc5-modules.yaml.gz
mv 87ada5e5d9c759dccdff8955fc93c33760454907021411ef552d3a6a8ca5ecc5-modules.yaml ../modules.yaml
cp 9d3cd6fcf9bdd9799b1c285b9d2d2627a8e4e5cd4e126bbfa8d8efea1722bde3-comps-AppStream.x86_64.xml ../
cd ..
rm -rf ./repodata
createrepo_c . -g 9d3cd6fcf9bdd9799b1c285b9d2d2627a8e4e5cd4e126bbfa8d8efea1722bde3-comps-AppStream.x86_64.xml
modifyrepo_c --mdtype=modules ./modules.yaml ./repodata/
----

At this point, you have properly regenerated the AppStream repository.

[discrete]
== End of Unit

link:../RHEL8-Workshop.adoc#toc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
