:sectnums:
:sectnumlevels: 3
:markup-in-source: verbatim,attributes,quotes
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


:toc:
:toclevels: 1

= Application Streams

== Overview

Application Streams are pre-packaged versions of runtime languages, web servers, databases, etc.

Example:

  * PHP 7.2 is an application stream
  * PHP 7.3 is an application stream
  * PostgreSQL 10 is an application stream
  
Application Streams allow multiple versions of things to be available for installation in RHEL.

Users can select the applications they want, select the version of the application that they want (the stream), and install and update the Application Stream on their system(s).

Application Streams:

  * are packaged as Modules, RPMs, and Software Collections (SCL).
  * are the mechanism of delivering and updating software at different speeds
  * allow developers to have bleeding-edge software, and server admins longer stability

== Getting Started

For these exercises, you will be using the host `node1` as user `root`.

From host `workstation`, ssh to `node1`.

[bash,options="nowrap",subs="{markup-in-source}"]
----
$ *ssh node1*
----

Use `sudo` to elevate your priviledges.

[bash,options="nowrap",subs="{markup-in-source}"]
----
$ *sudo -i*
----

Verify that you are on the right host for these exercises.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *cheat-appstream-checkhost.sh*
----

You are now ready to proceed with these exercises.

== Choosing an appstream module on RHEL 8.

Determine what modules are available.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *yum module list | grep postgresql*

postgresql           9.6         client, server [d]                       PostgreSQL server and client module
postgresql           10 [d]      client, server [d]                       PostgreSQL server and client module
postgresql           12          client, server                           PostgreSQL server and client module
----

This means that I can pick either the postgresql 10 stream (the default), the 9.6 stream, or the 12 stream. This enables me to use whichever postgresql best fits my needs. In the future as new postgresql versions come out, they
can be added as different streams that I can change to as well.
Switching streams is not supported. App Stream allows us to be more in
control with userspace than any previous version of RHEL.

On your new RHEL 8 system, if you do:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *yum install -y postgresql-server*

...<SNIP>...
  Installing       : postgresql-server-10.6-1.module+el8+2469+5ecd5aae.x86_64            3/3
  Running scriptlet: postgresql-server-10.6-1.module+el8+2469+5ecd5aae.x86_64            3/3
  Verifying        : libpq-12.1-3.el8.x86_64                                             1/3
  Verifying        : postgresql-10.6-1.module+el8+2469+5ecd5aae.x86_64                   2/3
  Verifying        : postgresql-server-10.6-1.module+el8+2469+5ecd5aae.x86_64            3/3

Installed:
  postgresql-server-10.6-1.module+el8+2469+5ecd5aae.x86_64      libpq-12.1-3.el8.x86_64
  postgresql-10.6-1.module+el8+2469+5ecd5aae.x86_64

Complete!
----

But let’s say that our application teams have a dependency on 9.6 but we
want to move to RHEL 8. With the app stream, we can do this. Let's do this next exercise on node3. 

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *exit*
----

Then:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *ssh node3*
----

INFO: You may need to `sudo -i` to elevate your priviledges.  Just make sure you're the `root` user.

On node3, let’s now run:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *yum module install -y postgresql:9.6/server*
----

The above command tells yum to install the server profile for postgresql
in the 9.6 version.

Once we’ve installed that, we will see:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *yum module list | grep postgresql*

postgresql           9.6 [e]      client, server [d] [i]                   PostgreSQL server and client module
postgresql           10 [d]       client, server [d]                       PostgreSQL server and client module
postgresql           12           client, server                           PostgreSQL server and client module     
----

The [e] by 9.6 means enabled. The [i] by server means installed.
Anywhere that we see a [d] it represents the default on the operating
system.

The server profile installs both the server and the client. If we just
wanted the client, we could remove the server profile:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *yum module remove -y postgresql:9.6/server*
----

and install only the client:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *yum module install -y postgresql:9.6/client*
----

Now let's inspect what yum tells us about the postgresql modules:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *yum module list | grep postgresql*
----

.Command Output
[source,indent=4]
----
postgresql           9.6 [e]      client [i], server [d]                   PostgreSQL server and client module                                         
postgresql           10 [d]       client, server [d]                       PostgreSQL server and client module                                         
postgresql           12           client, server                           PostgreSQL server and client module     
----

This shows us that the 9.6 stream is enabled and the client is installed, but the server is not. If the server were installed, it too would have a [i] in the output.

== Disabling application streams

Another interesting feature of application streams is the ability to
easily prevent packages from being installed. On node3.example.com, we
just installed postgresql. We don’t want to have another database on the
same machine and we see app stream profiles for mysql and mariadb. Let’s
disable these:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *yum module disable mariadb mysql -y*
----

Now when we do yum module list, we will see:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *yum module list | grep -e mariadb -e mysql*

mariadb                  10.3 [d][x]     client, server [d], galera                   MariaDB Module
mysql                    8.0 [d][x]      client, server [d]                           MySQL Module
----

The [x] stands for disabled. When we run:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *yum install mariadb -y*

No match for argument: mariadb
Error: Unable to find a match
----

To re-enable these app streams and allow the packages to be installed,
the command is:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *yum module enable mariadb mysql -y*
----

You may now switch back to the workstation:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *exit*
----

== Summary

[discrete]
=== Application Streams and Modules - Are they the same thing?

  * Application Streams are installable components with multiple versions available
    + Application Streams have a specified life, i.e. 5 years
  * Modules are the packaging used to build Application Streams
    + Modules have streams too, used to provide Application Streams
  * Module packaging will be used for lots of things in RHEL, not all modules will be supported Application Streams
    +Some modules are just single stream and some are just dependencies

== (BONUS) App Stream Automation with Ansible

WARNING: Depending on the workshop environment deployed, your workstation host may not have access to ansible.  In some cases, if your host does NOT have ansible installed, you may be able to install an unsupported version from the EPEL repo.  Only install the EPEL version if instructed to do so: `cheat-ansible-from-epel.sh`

App Stream operations can be performed in ansible with the 'dnf' module.  Here is a sample of a dnf task:

[source,options="nowrap",subs="{markup-in-source}"]
----
- name: install the postgresql 9.6 stream with the client profile.
  dnf:
    name: '@postgresql:9.6/client'
    state: present
----

A complete sample of a dnf based playbook for this cluster is provided on the workstation host.

As user `root` on the host `workstation`, run the following:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *cd /usr/local/src*

# *ansible-playbook -i appstream-inventory.yml appstream-playbook.yml*
----

Then to verify, you can use an ansible adhoc command to check your work.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *cd /usr/local/src*

# *ansible rhel8 -i appstream-inventory.yml -o -a "rpm -q postgresql-server"*

node1 | CHANGED | rc=0 | (stdout) postgresql-server-10.6-1.module+el8+2469+5ecd5aae.x86_64
node2 | FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"},"changed": true,"cmd": ["rpm","-q","postgresql-server"],"delta": "0:00:00.007318","end": "2020-05-01 17:28:38.719189","msg": "non-zero return code","rc": 1,"start": "2020-05-01 17:28:38.711871","stderr": "","stderr_lines": [],"stdout": "package postgresql-server is not installed","stdout_lines": ["package postgresql-server is not installed"],"warnings": ["Consider using the yum, dnf or zypper module rather than running 'rpm'.  If you need to use command because yum, dnf or zypper is insufficient you can add 'warn: false' to this command task or set 'command_warnings=False' in ansible.cfg to get rid of this message."]}
node3 | CHANGED | rc=0 | (stdout) postgresql-server-9.6.10-1.module+el8+2470+d1bafa0e.x86_64

----

NOTE: You will get an error from node2, since postgresql-server was not installed there

You should have:

  * postgresql-server 10.6 on node1
  * no postgresql-server on node2 (failed)
  * postgresql-server 9.6 on node3

== Additional Resources

Red Hat Documentation

    * link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_managing_and_removing_user-space_components/index[RHEL 8 Documentation: Installing, Managing, and Removing User Space Components]
    * link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_managing_and_removing_user-space_components/using-appstream_using-appstream[RHEL 8 Documentation: Using Appstream]
    

[discrete]
== End of Unit

ifdef::env-github[]
link:../RHEL8-Workshop.adoc#toc[Return to TOC]
endif::[]

////
Always end files with a blank line to avoid include problems.
////
