:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Boom

BOOM is a boot manager for Linux systems that support the 'BootLoader Specification' for boot entry configuration (ie: RHEL8 with GRUB2). It simplifies the creation of new or modified boot entries: for example, to boot snapshot images of the system created using LVM.

BOOM does not modify the existing boot loader configuration, and *only inserts* additional entries. The existing configuration is maintained, and any distribution integration, such as kernel installation and update scripts, continue to function as before.

BOOM also has a simple command-line interface (CLI) and API.

== Installation and Setup

The following set of instructions will install Boom.

Starting as user *root* on the host *workstation.example.com*, let’s ssh over to *node3.example.com*. No password should be required.

[root@workstation]#
----
ssh node3.example.com
----

Verify that you are on the right host for these exercises.

[root@node3]#
----
cheat-boom-checkhost.sh
----

[root@node3]# 
----
yum install -y boom-boot
----

That was easy!

== Add Capacity to Root LVM

In order to support LVM snapshots on the root volume, we need to add some addtional storage capacity.  The following command will create a new disk partition (/dev/vdb1) and add it to volume group “RHEL”.

[root@node3]
----
cheat-boom-addstorage.sh
----

You output should look list this.

[source, indent=4]
----
Clearing /dev/vdb
Creating new partition table on /dev/vdb

Welcome to fdisk (util-linux 2.32.1).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

Device does not contain a recognized partition table.
Created a new DOS disklabel with disk identifier 0xb8fd7055.

Command (m for help): Created a new DOS disklabel with disk identifier 0x4e3b8150.

Command (m for help): Partition type
   p   primary (0 primary, 0 extended, 4 free)
   e   extended (container for logical partitions)
Select (default p): Partition number (1-4, default 1): First sector (2048-20971519, default 2048): Last sector, +sectors or +size{K,M,G,T,P} (2048-20971519, default 20971519):
Created a new partition 1 of type 'Linux' and of size 10 GiB.

Command (m for help): The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.

Creating physical volume lable on /dev/vdb1
  Physical volume "/dev/vdb1" successfully created.
Extending volume group 'rhel' with /dev/vdb1
  Volume group "rhel" successfully extended
----

[NOTE]
====
_Native command(s) to add storage_
----
printf "o\nn\np\n\n\n\nw\n" | fdisk /dev/vdb

pvcreate /dev/vdb1

vgextend rhel /dev/vdb1
----
====


== Create some Important Stuff

The next set of instructions will create a file and a userID that we will remove and recover as part of this exercise:

[root@node3]
----
cheat-boom-importantstuff.sh
----

[NOTE]
====
_Native command(s) to create important file_
----
echo "This is an important file!!" > /root/importantfile
useradd importantuser

cat /root/importantfile

grep importantuser /etc/passwd
----
====

Your output should look like this

[source,indent=4]
----
Contents of 'importantfile':
This is an important file!!

Grepping 'importantuser' from /etc/passwd:
importantuser:x:1001:1001::/home/importantuser:/bin/bash
----

== Create System Snapshot

Start by creating a new logical volume to store the root snapshot

[root@node3]
----
lvcreate -s rhel/root -n root_snapshot -L 10G
----

Next we create a boom profile

[root@node3]
----
boom profile create --from-host --uname-pattern el8
----

Verify that the boom profile was created by the previous command.

[root@node3]
----
boom profile list
----

Take a snapshot of your root logical volume as a backup

[root@node3]
----
boom create --title "root LV snapshot" --rootlv rhel/root_snapshot
----

== Make Changes to System

Now we are going to remove the “importantfile” file and “importantuser” userID.

[root@node3]
----
rm -rf /root/importantfile 
userdel redhat
----

Confirm that our changes were effective

[root@node3]
----
cat /root/importantfile

grep redhat /etc/passwd
----

Your output should look like this

[source,indent=4]
----
This is an important file!!


----



== Reboot to Snapshot

WARNING: Bring up the virtual machine console for node3 before proceeding.  

We will now reset our host and boot the Logical Volume with the snapshot kernel in the grub menu.

[root@node3]
----
reboot
----

When the GRUB2 boot menu appears on the console, select “root LV snapshot” kernel to run, and hit enter.

=== Confirm Previous State of Host

Once the host is back online, ssh to back to *node3.example.com* and verify that the “importantfile” and “importantuser” exist in the backup snapshot:

[root@workstation]
----
ssh root@node3.example.com
----

[root@node3]
----
cat /root/importantfile

grep importantuser /etc/passwd
----

Your output should look like this

[source,indent=4]
----
This is an important file!!


----



== Return Host to Previous State

WARNING: Bring up the virtual machine console for node3 before proceeding.  

We will now reboot node3 virtual machine again into rescue mode and return the host to it's previous state.

[root@node3]
----
reboot
----

When the GRUB2 boot menu appears on the console, select “rescue”, and hit enter.

Once the host is back online, ssh to back to *node3.example.com*.

[root@workstation]
----
ssh root@node3.example.com
----

[root@node3]
----
lvconvert --merge /dev/rhel/root_snapshot
----

# set grub menu to boot default OS

[root@node3]# 
----
grub2-set-default 1
----

[root@node3]#
----
reboot
----

== Confirm System Restored

We have now recovered the missing data and userID. Now, let's make sure the restored data persisted.

[root@workstation ~]#
----
ssh root@node3.example.com
----

[root@node3]
----
cat /root/importantfile

grep importantuser /etc/passwd
----

Your output should look like this

[source,indent=4]
----
This is an important file!!
----

Wahoo! You are done.  If you have any questions, please ask.

== Additional Resources

Red Hat Documentation

    * link:https://https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8-beta/html/installing_identity_management_and_access_control/deploying-session-recording[Deplying Session Recording on Red Hat Enterprise Linux]

[discrete]
== End of Unit

link:../RHEL8-Workshop.adoc#toc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
