:sectnums:
:sectnumlevels: 3
:markup-in-source: verbatim,attributes,quotes
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:toc:
:toclevels: 1

= Boom

== Overview

BOOM is a boot manager for Linux systems that support the 'BootLoader Specification' for boot entry configuration (ie: RHEL8 with GRUB2). It simplifies the creation of new or modified boot entries: for example, to boot snapshot images of the system created using LVM.

BOOM does not modify the existing boot loader configuration, and *only inserts* additional entries. The existing configuration is maintained, and any distribution integration, such as kernel installation and update scripts, continue to function as before.

BOOM also has a simple command-line interface (CLI) and API.

The object of this exercise is quite simple.  We care going to create an alternative boot entry which 
will load the same kernel with a few additional detectable parameters.

== Getting Started

For these exercises, you will be using the host `node3` as user `root`.

From host `workstation`, ssh to `node3`.

[bash,options="nowrap",subs="{markup-in-source}"]
----
$ *ssh node3*
----

Use `sudo` to elevate your priviledges.

[bash,options="nowrap",subs="{markup-in-source}"]
----
$ *sudo -i*
----

Verify that you are on the right host for these exercises.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *cheat-boom-checkhost.sh*
----

You are now ready to proceed with these exercises.

== Installation

The following set of instructions will install Boom.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *yum install -y boom-boot*
----

That was easy!

== Create Profile

Creating a new boot entry begins with a boom `profile`.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *boom profile create --from-host --uname-pattern el8*

Created profile with os_id f44fb52:
  OS ID: "f44fb528ff8360ad67e2fe0274750b838da0bd6a",
  Name: "Red Hat Enterprise Linux", Short name: "rhel",
  Version: "8.1 (Ootpa)", Version ID: "8.1",
  UTS release pattern: "el8",
  Kernel pattern: "/vmlinuz-%{version}", Initramfs pattern: "/initramfs-%{version}.img",
  Root options (LVM2): "rd.lvm.lv=%{lvm_root_lv}",
  Root options (BTRFS): "rootflags=%{btrfs_subvolume}",
  Options: "root=%{root_device} ro %{root_opts}",
  Title: "%{os_name} %{os_version_id} (%{version})"
----

Verify that the boom profile was created by the previous command.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *boom profile list*

OsID    Name                     OsVersion
f44fb52 Red Hat Enterprise Linux 8.1 (Ootpa)
----

== Create GRUB Entry

Now to create a boot entry for grub which utilizes the snapshot as the boot volume.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *boom create --title "Alt Kernel Parms" --root-device /dev/vda1*

WARNING - Boom grub2 integration is disabled in '/boot/../etc/default/boom'
Created entry with boot_id 40d2351:
  title Alt Kernel Parms
  machine-id 298b11e40a1e46a5a1ce834b845cc51b
  version 4.18.0-147.el8.x86_64
  linux /vmlinuz-4.18.0-147.el8.x86_64
  initrd /initramfs-4.18.0-147.el8.x86_64.img
  options root=/dev/vda1 ro
----

Take a look at currently configured boom-boot entries.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *boom entry list*

BootID  Version                  Name                     RootDevice
40d2351 4.18.0-147.el8.x86_64    Red Hat Enterprise Linux /dev/vda1
----

Add custom kernel option

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *boom entry edit 40d2351 --os-options "custom_val"*
----

Show details about our boom-boot entry.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *boom entry show 40d2351*

Boot Entry (boot_id=40d2351)
  title Alt Kernel Parms
  machine-id 298b11e40a1e46a5a1ce834b845cc51b
  version 4.18.0-147.el8.x86_64
  linux /vmlinuz-4.18.0-147.el8.x86_64
  initrd /initramfs-4.18.0-147.el8.x86_64.img
  options root=/dev/vda1 ro
----


== Reboot to Alternate Entry

WARNING: If possible, bring up the virtual machine console for node3 before proceeding.  

Before reboot, there are 2 options to invoke the right loader at restart:
  . enter the GRUB menu and select at boot time
  . use grub-set-default to preselect which one to load
  
We are going to opt for preselect since it's just easier.  Use the following cheat to inspect 
the currently configured GRUB menu options.

.[root@node3]#
[bash,options="nowrap",subs="{markup-in-source}"]
----
# *cheat-boom-grublist.sh*

0  title="root LV snapshot"
1  title="Red Hat Enterprise Linux (4.18.0-67.el8.x86_64) 8.0 (Ootpa)"
2  title="Red Hat Enterprise Linux (0-rescue-e988045b45b04b11b84741d6a568861b) 8.0 (Ootpa)"
----

We want to reboot to our snapshot, so in this case we use '0'.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *grub2-set-default 0*
----

Verify that the parameters stuck.  Notice that "saved_entry=0", that's what we want.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *grub2-editenv list*

saved_entry=0
kernelopts=root=/dev/mapper/rhel-root_snapshot ro crashkernel=auto resume=/dev/mapper/rhel-swap rd.lvm.lv=rhel/root rd.lvm.lv=rhel/swap rhgb quiet
boot_success=0
----

We will now reset our host and boot the snapshot Logical Volume.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *reboot*
----

=== Confirm Previous State of Host

Once the host is back online, ssh to back to `node3` and verify that the alternate kernel parameters are active.

.[root@workstation]#
[bash,options="nowrap",subs="{markup-in-source}"]
----
# *cat /proc/cmdline*
----



Wahoo! You are done.  If you have any questions, please ask.

== Additional Resources

    * link:https://systemd.io/BOOT_LOADER_SPECIFICATION.html[Boot Loader Specification]

[discrete]
== End of Unit

////
Always end files with a blank line to avoid include problems.
////
