:sectnums:
:sectnumlevels: 2
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:toc:
:toclevels: 1

= Building with Buildah and Inspecting with Skopeo!

In this unit, we will get familiar with Buildah and Skopeo!

[discrete]
== Additional Reference Materials


NOTE: You are not required to reference any additional resources for these exercises.  This is informational only.

    * link:https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image?sc_cid=701f2000000txokAAA&utm_source=bambu&utm_medium=social&utm_campaign=abm[Introducing the Red Hat Universal Base Image - Scott McCarty]
    * link:https://developers.redhat.com/blog/2018/11/20/buildah-podman-containers-without-daemons/[Containers without daemons: Podman and Buildah available in RHEL 7.6 and RHEL 8 Beta - Tom Sweeney]
    * link:https://linuxhandbook.com/buildah-basics/[Getting Started with Buildah - Servesha]

== Getting Started

From workstation.example.com, you should be able to ssh to node3.example.com as 'root' without any prompts for credentials.

.[root@workstation ~]#
----
ssh node3.example.com
----

Verify that you are on the right host for these exercises.

.[root@node3 ~]#
----
cheat-buildah-checkhost.sh
----

Now you are ready to extend your knowledge of containers with buildah and skopeo.

== Build an Image With Buildah

=== Web Server Version 2.0

In the previous lab on `podman`, we pulled down the ubi image and used an OCIFile to build a "webserver" container image. That process used `buildah` under the hood, but in this lab we are going to use `buildah` directly. 

==== Start a Fresh Build

Let's get started by creating a new working container based off of the ubi image.

.[root@node3 ~]#
----
buildah from ubi8/ubi
----

.Your output should look like this
[source]
----
Getting image source signatures
Copying blob befb03b11956 done
Copying blob ee2244abc66f done
Copying config 8121a9f530 done
Writing manifest to image destination
Storing signatures
ubi-working-container
----

This gives us the name of the "working container" and it is this container image that we will modify with buildah.

==== Add a Custom File

Let's run:

.[root@node3 ~]#
----
echo "Every time you run setenforce 0, you make Dan Walsh weep." > /root/dan-cries.txt

buildah copy ubi-working-container /root/dan-cries.txt /var/www/html/
----

At this point, you have copied your local `dan-cries.txt` into the the ubi-working-container image.

You should see feedback similar to:

----
34f1621a22ffd90a2ebbd58eba315089dc2704ac69a3d33d60362422e4ec26a1
----

The steps you perfromed above is equivalent to the following OCIFile (or Dockerfile):

----
FROM ubi8/ubi
COPY /root/dan-cries.txt /var/www/html/
----

So it's nice that we can do that with buildah, manually.

But wait there's more!!!

==== Install Packages

We need to install an httpd server in our image, and what better way to do that than a simple `yum install`.

.[root@node3 ~]#
----
buildah run ubi-working-container yum install -y httpd
----

==== Configure the Entry Point

Next we set the entry point (command) so when the image deploys it knows what process to launch.

.[root@node3 ~]#
----
buildah config --cmd "/usr/sbin/httpd -D FOREGROUND" ubi-working-container
----

==== Mount the Container Image

Now let us continue to explore and make additional cutomizations to our image.

Proceed to mount the root filesystem of your container with:

.[root@node3 ~]#
----
buildah mount ubi-working-container
----

You should see output similar to:

[source]
----
/var/lib/containers/storage/overlay/3456a159b5b3c9e3056d14b97bde1f0e770500dd1cdd6168c894a52a3b3f12ee/merged
----

Using the long path provided by your mount command, change directories.

.[root@node3 ~]#
----
cd /var/lib/containers/storage/overlay/3456a159b5b3c9e3056d14b97bde1f0e770500dd1cdd6168c894a52a3b3f12ee/merged
ls -lah ./var/www/html
----

and you should see:

----
total 16K
drwxr-xr-x. 2 root root 4.0K Apr 12 21:12 .
drwxr-xr-x. 3 root root 4.0K Apr 12 21:12 ..
-rw-r--r--. 1 root root   58 Apr 12 21:12 dan-cries.txt
----

There is our `dan-cries.txt`! Let's add an additional file: ./var/www/html/index.html:

----
<html>
<title>Stop Disabling SELinux</title>
<body>
<p>
Seriously, stop disabling SELinux. Learn how to use it before you blindly shut it off.
</p>
</body>
</html>
----

Once you have written that, you should be able to run:

.[root@node3 merged]#
----
ls -lahZ ./var/www/html/
----

and see:

----
total 20K
drwxr-xr-x. 2 root root system_u:object_r:container_file_t:s0:c60,c544 4.0K Apr 12 21:25 .
drwxr-xr-x. 3 root root system_u:object_r:container_file_t:s0:c60,c544 4.0K Apr 12 21:12 ..
-rw-r--r--. 1 root root system_u:object_r:container_file_t:s0:c60,c544   58 Apr 12 21:12 dan-cries.txt
-rw-r--r--. 1 root root system_u:object_r:container_file_t:s0:c60,c544  164 Apr 12 21:24 index.html
----

When you are done making direct changes to the root filesystem of your container, you can run:

.[root@node3 merged]#
----
cd /root
buildah unmount ubi-working-container
----

You should see output similar to:
----
e918debcaabb5820997b1a4969fbd45284adc0a2869d1f22a1bce78f703ff3c6
----

==== Commit Changes to New Image

At this point, we've used buildah to run commands and create a container image similar to those in the OCIFile used in the `podman` unit.  Go ahead and commit the working container in to an actual container image:

.[root@node3 ~]#
----
buildah commit ubi-working-container webserver2
----

You should see output similar to:

[source]
----
Getting image source signatures
Copying blob d3ada5af5602 skipped: already exists
Copying blob 668db11eda93 skipped: already exists
Copying blob 0f75b7e04ec6 done
Copying config a831badcea done
Writing manifest to image destination
Storing signatures
a831badcea41e924fd4a37f98431702142c17a64d06bd5444ac4471c1285be50
----

Let's look at our images:

.[root@node3 ~]#
----
podman images
----

You should see:

[source]
----
REPOSITORY                            TAG      IMAGE ID       CREATED          SIZE
localhost/webserver2                  latest   a831badcea41   25 seconds ago   240 MB
registry.access.redhat.com/ubi8/ubi   latest   8121a9f5303b   12 days ago      240 MB
----

==== Deploy

Now let's run that webserver:

.[root@node3 ~]#

[source]
----
podman run -d -p 8080:80 webserver2
----

==== Validate

Finally let's test our new webserver:

.[root@node3 ~]#

[source]
----
curl http://localhost:8080/
----

returns:

[source]
----
<html>
<title>Stop Disabling SELinux</title>
<body>
<p>
Seriously, stop disabling SELinux. Learn how to use it before you blindly shut i
t off.
</p>
</body>
</html>
----

and:

.[root@node3 ~]#
----
curl http://localhost:8080/dan-cries.txt
----

returns:

[source]
----
Every time you run setenforce 0, you make Dan Walsh weep.
----

As you can see, all of the changes we made with buildah are active and working in this new container image!




== Inspecting Images with Skopeo

Let's take a look at the webserver2:latest container that we just built:

.[root@node3 ~]#

[source]
----
skopeo inspect containers-storage:localhost/webserver2:latest
----

This should show us output similar to:

[source]
----
{
    "Name": "localhost/webserver2",
    "Digest": "sha256:15ad1feee74c68a16031b2120793873432572d2592e0818bc4cff9842696b651",
    "RepoTags": [],
    "Created": "2020-04-13T02:17:40.873320811Z",
    "DockerVersion": "",
    "Labels": {
        "architecture": "x86_64",
        "authoritative-source-url": "registry.access.redhat.com",
        "build-date": "2020-03-31T14:54:13.907559",
        "com.redhat.build-host": "cpt-1007.osbs.prod.upshift.rdu2.redhat.com",
        "com.redhat.component": "ubi8-container",
        "com.redhat.license_terms": "https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI",
        "description": "The Universal Base Image is designed and engineered to be the base layer for all of your containerized applications, middleware and utilities. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.",
        "distribution-scope": "public",
        "io.k8s.description": "The Universal Base Image is designed and engineered to be the base layer for all of your containerized applications, middleware and utilities. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.",
        "io.k8s.display-name": "Red Hat Universal Base Image 8",
        "io.openshift.expose-services": "",
        "io.openshift.tags": "base rhel8",
        "maintainer": "Red Hat, Inc.",
        "name": "ubi8",
        "release": "408",
        "summary": "Provides the latest release of Red Hat Universal Base Image 8.",
        "url": "https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8/images/8.1-408",
        "vcs-ref": "26f36bfa3e3a04c8c866b250924c1aefc34f01c9",
        "vcs-type": "git",
        "vendor": "Red Hat, Inc.",
        "version": "8.1"
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:d3ada5af5602bd0da378e4f0144f8fe8bdbe3f5a65f367dd9ebe759756bada68",
        "sha256:668db11eda933a46ae8030a8643b96088218dae0efeac54bc6dbc88488725c1b",
        "sha256:d9142adf6c6796bbbccc6065c57508e87138921d3aea0e9fc368f9861606da68"
    ]
}
----

We will see that this container is based on the Red Hat UBI image. 

Let's look at the ubi8/ubi container that we built this off of and compare the layers section:

.[root@node3 ~]#
----
skopeo inspect containers-storage:registry.access.redhat.com/ubi8/ubi:latest
----

The output of this should be similar to:

----
{
    "Name": "registry.access.redhat.com/ubi8/ubi",
    "Digest": "sha256:f6648a87c8c52099bacd19b112beb3b65407ae6d3441f9b559ba53c4112c57a4",
    "RepoTags": [],
    "Created": "2020-03-31T14:54:42.119985Z",
    "DockerVersion": "1.13.1",
    "Labels": {
        "architecture": "x86_64",
        "authoritative-source-url": "registry.access.redhat.com",
        "build-date": "2020-03-31T14:54:13.907559",
        "com.redhat.build-host": "cpt-1007.osbs.prod.upshift.rdu2.redhat.com",
        "com.redhat.component": "ubi8-container",
        "com.redhat.license_terms": "https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI",
        "description": "The Universal Base Image is designed and engineered to be the base layer for all of your containerized applications, middleware and utilities. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.",
        "distribution-scope": "public",
        "io.k8s.description": "The Universal Base Image is designed and engineered to be the base layer for all of your containerized applications, middleware and utilities. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.",
        "io.k8s.display-name": "Red Hat Universal Base Image 8",
        "io.openshift.expose-services": "",
        "io.openshift.tags": "base rhel8",
        "maintainer": "Red Hat, Inc.",
        "name": "ubi8",
        "release": "408",
        "summary": "Provides the latest release of Red Hat Universal Base Image 8.",
        "url": "https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8/images/8.1-408",
        "vcs-ref": "26f36bfa3e3a04c8c866b250924c1aefc34f01c9",
        "vcs-type": "git",
        "vendor": "Red Hat, Inc.",
        "version": "8.1"
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:ee2244abc66ff9c6a4bf50fe19041fec82a95c87d18ee3a3660368cb274927c7",
        "sha256:befb03b11956169cf23096fc58081ca35034a6545fc37d63605bf0d200fe5eda"
    ]
}
----

and comparing the layers section, we can see that our container has 3 layers whereas the original container only has 2 layers. In this, we can tell that there are differences between these containers.

Pretty neat that we can look inside local containers, but what about containers that are in registries? Skopeo can inspect containers on remote registries without the need to pull the image locally. Let's give that a test:

.[root@node3 ~]#
----
skopeo inspect --tls-verify=false docker://core.example.com:5000/rhel7.5
----

The above allows us to look at our insecure registry's copy of RHEL 7.5 and will return this output:

[source]
----
{
    "Name": "core.example.com:5000/rhel7.5",
    "Digest": "sha256:dff4dc848def191bc8fc2185a8ff57b4d4fdbf032457b28286b381bf0238e2c5",
    "RepoTags": [
        "latest"
    ],
    "Created": "2018-09-19T20:47:02.057298Z",
    "DockerVersion": "1.12.6",
    "Labels": {
        "architecture": "x86_64",
        "authoritative-source-url": "registry.access.redhat.com",
        "build-date": "2018-09-19T20:46:28.459833",
        "com.redhat.build-host": "osbs-cpt-003.ocp.osbs.upshift.eng.rdu2.redhat.com",
        "com.redhat.component": "rhel-server-container",
        "description": "The Red Hat Enterprise Linux Base image is designed to be a fully supported foundation for your containerized applications. This base image provides your operations and application teams with the packages, language runtimes and tools necessary to run, maintain, and troubleshoot all of your applications. This image is maintained by Red Hat and updated regularly. It is designed and engineered to be the base layer for all of your containerized applications, middleware and utilities. When used as the source for all of your containers, only one copy will ever be downloaded and cached in your production environment. Use this image just like you would a regular Red Hat Enterprise Linux distribution. Tools like yum, gzip, and bash are provided by default. For further information on how this image was built look at the /root/anacanda-ks.cfg file.",
        "distribution-scope": "public",
        "io.k8s.description": "The Red Hat Enterprise Linux Base image is designed to be a fully supported foundation for your containerized applications. This base image provides your operations and application teams with the packages, language runtimes and tools necessary to run, maintain, and troubleshoot all of your applications. This image is maintained by Red Hat and updated regularly. It is designed and engineered to be the base layer for all of your containerized applications, middleware and utilities. When used as the source for all of your containers, only one copy will ever be downloaded and cached in your production environment. Use this image just like you would a regular Red Hat Enterprise Linux distribution. Tools like yum, gzip, and bash are provided by default. For further information on how this image was built look at the /root/anacanda-ks.cfg file.",
        "io.k8s.display-name": "Red Hat Enterprise Linux 7",
        "io.openshift.expose-services": "",
        "io.openshift.tags": "base rhel7",
        "maintainer": "Red Hat, Inc.",
        "name": "rhel7",
        "release": "433",
        "summary": "Provides the latest release of Red Hat Enterprise Linux 7 in a fully featured and supported base image.",
        "url": "https://access.redhat.com/containers/#/registry.access.redhat.com/rhel7/images/7.5-433",
        "usage": "This image is very generic and does not serve a single use case. Use it as a base to build your own images.",
        "vcs-ref": "b8a2783c87bd09059fb8ba8a00817734bcb48ac3",
        "vcs-type": "git",
        "vendor": "Red Hat, Inc.",
        "version": "7.5"
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:610a5431dd245b77764e5d75b832fbca851ed570b1c42bce9c714c3ba147861f",
        "sha256:cf34c53464e2338149074d94dc278ff376502bc359dc42046e6a60be47729888"
    ]
}
----

Let's run:

.[root@node3 ~]#
----
podman images
----

and note that rhel7.5 is not in our list:

[source]
----
REPOSITORY                             TAG      IMAGE ID       CREATED        SIZE
localhost/website2                     latest   b5ab9d495626   23 hours ago   323 MB
localhost/custom_image                 latest   611116f647ab   23 hours ago   323 MB
core.example.com:5000/httpd-24-rhel7   latest   0f1cb8c3c29b   2 weeks ago    323 MB
core.example.com:5000/ubi              latest   c096c0dc7247   2 weeks ago    214 MB
localhost/myfavorite                   latest   c096c0dc7247   2 weeks ago    214 MB
----

=== Obtaining tarballs of containers in remote registries for further inspection

Let's run:

.[root@node3 ~]#
----
mkdir /root/rhel7.5tarball
skopeo --tls-verify=false copy docker://core.example.com:5000/rhel7.5 dir:/root/rhel7.5tarball
----

You will see output like:

----
WARN[0000] '--tls-verify' is deprecated, please set this on the specific subcommand
Getting image source signatures
Copying blob sha256:610a5431dd245b77764e5d75b832fbca851ed570b1c42bce9c714c3ba147861f
 74.68 MB / 74.68 MB [======================================================] 2s
Copying blob sha256:cf34c53464e2338149074d94dc278ff376502bc359dc42046e6a60be47729888
 1.32 KB / 1.32 KB [========================================================] 0s
Copying config sha256:7b875638cfd87edc473e80774d979a8ddd555e13c6f33db9b712b5d4be244411
 6.52 KB / 6.52 KB [========================================================] 0s
Writing manifest to image destination
Storing signatures
----

and now we can do:

.[root@node3 ~]#
----
cd /root/rhel7.5tarball
ls -l
----

and see:

----
total 76492
-rw-r--r--. 1 root root 78307258 May  3 13:48 610a5431dd245b77764e5d75b832fbca851ed570b1c42bce9c714c3ba147861f
-rw-r--r--. 1 root root     6680 May  3 13:48 7b875638cfd87edc473e80774d979a8ddd555e13c6f33db9b712b5d4be244411
-rw-r--r--. 1 root root     1350 May  3 13:48 cf34c53464e2338149074d94dc278ff376502bc359dc42046e6a60be47729888
-rw-r--r--. 1 root root      590 May  3 13:48 manifest.json
-rw-r--r--. 1 root root       33 May  3 13:48 version
----

Inspecting the images, we get:

.[root@node3 ~]#
----
file 610a5431dd245b77764e5d75b832fbca851ed570b1c42bce9c714c3ba147861f
----

which shows us:

----
610a5431dd245b77764e5d75b832fbca851ed570b1c42bce9c714c3ba147861f: gzip compressed data, original size 210667520
----

Let's add a .tar.gz suffix: (I peaked ahead -- inside that gz is a tar!)

.[root@node3 ~]#
----
mv 610a5431dd245b77764e5d75b832fbca851ed570b1c42bce9c714c3ba147861f 610a5431dd245b77764e5d75b832fbca851ed570b1c42bce9c714c3ba147861f.tar.gz
tar xvzf 610a5431dd245b77764e5d75b832fbca851ed570b1c42bce9c714c3ba147861f.tar.gz
----

Once done, we can execute:

.[root@node3 ~]#
----
ls -l
----

and see output similar to:

[source]
----
total 71584
-rw-r--r--.  1 root root 73273413 May  3 13:48 610a5431dd245b77764e5d75b832fbca851ed570b1c42bce9c714c3ba147861f.tar.gz
-rw-r--r--.  1 root root     6680 May  3 13:48 7b875638cfd87edc473e80774d979a8ddd555e13c6f33db9b712b5d4be244411
lrwxrwxrwx.  1 root root        7 Sep 19  2018 bin -> usr/bin
dr-xr-xr-x.  2 root root        6 Dec 14  2017 boot
-rw-r--r--.  1 root root     1350 May  3 13:48 cf34c53464e2338149074d94dc278ff376502bc359dc42046e6a60be47729888
drwxr-xr-x.  2 root root        6 Sep 19  2018 dev
drwxr-xr-x. 49 root root     4096 Sep 19  2018 etc
drwxr-xr-x.  2 root root        6 Sep 19  2018 home
lrwxrwxrwx.  1 root root        7 Sep 19  2018 lib -> usr/lib
lrwxrwxrwx.  1 root root        9 Sep 19  2018 lib64 -> usr/lib64
-rw-r--r--.  1 root root      590 May  3 13:48 manifest.json
drwxr-xr-x.  2 root root        6 Dec 14  2017 media
drwxr-xr-x.  2 root root        6 Dec 14  2017 mnt
drwxr-xr-x.  2 root root        6 Dec 14  2017 opt
drwxr-xr-x.  2 root root        6 Sep 19  2018 proc
dr-xr-x---.  3 root root      154 Sep 19  2018 root
drwxr-xr-x. 12 root root      145 Sep 19  2018 run
lrwxrwxrwx.  1 root root        8 Sep 19  2018 sbin -> usr/sbin
drwxr-xr-x.  2 root root        6 Dec 14  2017 srv
drwxr-xr-x.  2 root root        6 Sep 19  2018 sys
drwxrwxrwt.  7 root root      132 Sep 19  2018 tmp
drwxr-xr-x. 13 root root      155 Sep 19  2018 usr
drwxr-xr-x. 18 root root      238 Sep 19  2018 var
-rw-r--r--.  1 root root       33 May  3 13:48 version
----

At this point, you can go dive into the filesystem and do any analysis you would like. Remember, we pulled this container image direct from the registry without adding it to the list of images available to podman for deployment.

The other two numeric files provided in the download are a copy of the metadata in text (7b875638cfd87edc473e80774d979a8ddd555e13c6f33db9b712b5d4be244411 in this specific example) and a tarball of any container secrets and the file used to build the container. The following is the output of tar on that file:

[source]
----
etc/
etc/yum.repos.d/
run/
run/secrets/
root/
root/buildinfo/
root/buildinfo/Dockerfile-rhel7-7.5-433
----


=== Other Uses of Skopeo

Skopeo can also do the following things:

  * Copy an image (manifest, filesystem layers, signatures) from one location to another. It can convert between manifest types in doing this (oci, v2s1, v2s2)
  * Delete images from registries that you have admin rights to.
  * Push images to registries that you have push rights to.

Examples of how to do these things are available in 'man skopeo'

=== Cleanup

.[root@node3 ~]#
----
buildah kill --all

buildah rm --all

buildah rmi --all
----

Now you are ready to proceed to the next unit.

[discrete]
== End of Unit

link:../RHEL8-Workshop.adoc#toc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
