:sectnums:
:sectnumlevels: 3
:markup-in-source: verbatim,attributes,quotes
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:toc:
:toclevels: 1

= Documentation Conventions

This guide is intended to support a series of workshop exercises for individuals getting familiar with Red Hat Enterprise Linux 8.  What follows are examples of how this document is formatted and expected to be consumed.

[discrete]
== Tips, Notes & Warnings

TIP: Extra info which could be helpful, but not essential for a given task or discussion

NOTE: Special information to pay attention

WARNING: Critical information which could help you avoid major set backs

[discrete]
== Executing tasks on the CLI

[discrete]
=== Input

Each block of commands to execute will be labeled with the expected *user-id* and *host*.  To enhance cut & paste efficiency, the command prompt is omitted from each line.

.[root@master ~]#
----
systemctl status sshd
----

[discrete]
=== Output

Sample output will be titled with _'Your output should look like this'_ (or _'Command Output'_) and also be indented to help with visual identification.  Sometimes there will also be footnotes and/or callouts.

.Command Output
[source,indent=4]
----
● sshd.service - OpenSSH server daemon
   Loaded: loaded (/usr/lib/systemd/system/sshd.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-02-26 12:04:16 EST; 27min ago // <1>
     Docs: man:sshd(8)
           man:sshd_config(5)
 Main PID: 3094 (sshd)
   CGroup: /system.slice/sshd.service
           └─3094 /usr/sbin/sshd -D
...<snip>...
----
<1> This is the line we are interested in with a special note

[discrete]
=== Alternate Commands

The workshop often provides cheat-scripts to ease certain complex tasks.  This helps the class stay focused and reduces the likelihood of errors and disruptions to the workshop delivery.  Honestly, we are not here to learn `vi`, `emacs` or start debates about the merits of `sed` and `awk`.

The native commands which the cheat-scripts utilize will be documented in the following way.

.[root@master ~]#
----
cheat-service-status.sh
----

[NOTE]
====
_Native command(s) to verify system service_
----
systemctl status sshd
----
====

[discrete]
== End of Unit

link:../RHEL8-Workshop.adoc[Return to Document]

////
Always end files with a blank line to avoid include problems.
////
