:sectnums:
:sectnumlevels: 3
:markup-in-source: verbatim,attributes,quotes
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:toc:
:toclevels: 1

= Migrating from Non-RHEL to RHEL

WARNING: THIS UNIT IS A WORK IN PROGRESS AND NOT COMPLETE

== Overview

WARNING:  This unit will only function if the workshop environment is provisioned with a local Satellite Server OR if the client is registered to redhat.com.  Please consult the instructor for directions before proceeding.

In this unit, we will get familiar with the tool called migrate2rhel.

== Getting Started

For these exercises, you will be using the host `node4` as user `root`.  Before you begin, confirm the node was provisioned with CentOS 7

From host `bastion`, ssh to `node4`.

[bash,options="nowrap",subs="{markup-in-source}"]
----
$ *ssh node4*
----

Use `sudo` to elevate your priviledges.

[bash,options="nowrap",subs="{markup-in-source}"]
----
$ *sudo -i*
----

Verify that you are on the right host for these exercises.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *workshop-c2r-checkhost.sh*
----

You are now ready to proceed with these exercises.

== Pre Conversion Preperation

=== Conflict Resolution

I know this kernel module creates a conflict, so blacklist it and reboot

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
echo "blacklist nfnetlink" >> /etc/modprobe.d/convert2rhel.conf
----

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
reboot
----

=== Certificates and Configurations

Download the Red Hat GPG key:

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
curl -o /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release https://www.redhat.com/security/data/fd431d51.txt
----

Download the SSL certificate of the https://cdn.redhat.com server, which contains the Convert2RHEL repositories:

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
curl --create-dirs -o /etc/rhsm/ca/redhat-uep.pem https://ftp.redhat.com/redhat/convert2rhel/redhat-uep.pem
----

Install the Convert2RHEL repository file:

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
curl -o /etc/yum.repos.d/convert2rhel.repo https://ftp.redhat.com/redhat/convert2rhel/7/convert2rhel.repo
----

I'm using a local satellite for this demonstration.
Download the consumer RPM.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
curl --create-dirs --insecure --output /usr/share/convert2rhel/subscription-manager/katello-ca-consumer-latest.noarch.rpm http://satellite.sat6ovirt.example.com/pub/katello-ca-consumer-latest.noarch.rpm
----

=== Software Installation

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
yum -y install convert2rhel
----

== Run the conversion

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
convert2rhel -y --org ExampleCom --activationkey MyKey-DEV
----

== Post Conversion Cleanup

=== Disable Conflicting Repos

Disable the CentOS repos

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
yum-config-manager --disable my-centos-7-rpms
----

Reboot

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
reboot
----

=== Validation

Validate the installed OS release

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
cat /etc/redhat-release
----

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
lsb_release --all
----

Inspect installed packages and their repo origin.  Just about everything should be from a rhel-7-server-rpms or equivalent repo.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
yum list installed
----

=== Optional

Remove third-party packages from the original OS that remained unchanged (typically packages that do not have a RHEL counterpart). To get a list of these packages, use:

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
yum list extras --disablerepo="*" --enablerepo=rhel-7-server-rpms
----

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
yum remove yum-plugin-fastestmirror
----


== Summary


[discrete]
== Additional Reference Materials

* link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/converting_from_an_rpm-based_linux_distribution_to_rhel/index[Converting From An RPM-Based Linux Distribution to RHEL]

[discrete]
== End of Unit

ifdef::env-github[]
link:../RHEL8-Workshop.adoc#toc[Return to TOC]
endif::[]

////
Always end files with a blank line to avoid include problems.
////
