:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Firewalld - Firewall Service Management

The *firewalld* daemon provides a dynamically managed firewall (network security) with support for network “zones” which assign a level of trust to a network, its associated connections and interfaces. 

Few additonal features of firewalld include:

  * support for IPv4 and IPv6 settings
  * support for ethernet bridges
  * separation of runtime and permanent configuration options
  * interface for external services to manage firewall rules directly

Firewalld stores it in various configuration XML files in 2 places:

  * /usr/lib/firewalld/ 
  * /etc/firewalld/

WARNING: Both firewalld and nftables can be used to manage the kernel's network packet filter. Administrators should pick one tool as they will interfere with one another if used simultaneously.  Do not use them both.

Note: Use `systemctl mask` to ensure that only one or the other service may be started, even if both are available on the system.  Refer to the systemd unit for further information.

== Getting Started

Starting on the host *workstation.example.com*, let's ssh over to *node2.example.com*.  No password should be required.

.[root@workstation]#
----
ssh node1.example.com
----

Verify that you are on the right host for these exercises.

.[root@node3]#
----
cheat-firewalld-checkhost.sh
----

Now you are ready to begin

== Installation

Firewalld is already installed and running on you host. These steps provided here will restore firewalld if it has been disabled. It should NOT be necessary to run these commands in this lab.

[NOTE]
====
_Native command(s) to enable firewalld_
----
systemctl stop nftables
systemctl disable nftables
yum install firewalld
systemctl enable --now firewalld 
systemctl status -l firewalld 
----
====

== Configuration

Firewalld uses several different, completely adaptable, XML config files to store configurations. These files also ensure run-time and persistent configuration separation. The default configuration files are in */usr/lib/firewalld*, while user customized files (which take precedence if they exist) are in */etc/firewalld*. 

== Zones

Firewald uses zones to assign a level of trust to a network and its associated connections and interfaces. The zone files include definitions of Services, Ports (ranges) with protocols, Rich rules, Internet Control Message Protocol (ICMP) blocks , Masquerading and Port/packet forwarding. There are several built-in zones: block, dmz, drop, external, home, internal, public, trusted, work - and you can also create new zones 

Each zone is similar to a complete firewall and there is a single zone selection per environment or connection. The public zone is the Initial default. Zones are identified in ifcfg files or NetworkManager configuration using: ZONE=<name> 

Let us examine a couple of the system's default zone files in */usr/lib/firewalld/zones*

.public.xml
[source,indent=4]
----
<?xml version="1.0" encoding="utf-8"?> 
<zone>
	<service name="ssh"/>
	<service name="dhcpv6-client"/>
</zone>
----

.drop.xml
[source,indent=4]
----
<?xml version="1.0" encoding="utf-8"?>
<zone target="DROP">
  <short>Drop</short>
  <description>Unsolicited incoming network packets are dropped. Incoming packets that are related to outgoing network connections are accepted. Outgoing network connections are allowed.</description>
</zone>
----

== Services

There are nearly 50 built-in services files shipped with firewalld. Services files include Port (ranges) with protocol, Netfilter helper modules, and destination address (range) for IPv4 and/or IPv6. You can also create your own services files or customize the default files. To customize a file, simply copy it from /usr/lib/firewalld/services to /etc/firewalld/services then make any required changes. 

Here are a couple common configs for services defined in */usr/lib/firewalld/services *.

.http.xml
[source,indent=4]
----
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>SSH</short>
  <description>Secure Shell (SSH) is a protocol for logging into and executing commands on remote machines. It provides secure encrypted communications. If you plan on accessing your machine remotely via SSH over a firewalled interface, enable this option. You need the openssh-server package installed for this option to be useful.</description>
  <port protocol="tcp" port="22"/>
</service>
----

.http.xml
[source,indent=4]
----
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>WWW (HTTP)</short>
  <description>HTTP is the protocol used to serve Web pages. If you plan to make your Web server publicly available, enable this option. This option is not required for viewing pages locally or developing Web pages.</description>
  <port protocol="tcp" port="80"/>
</service>
----













== Additional Resources

Red Hat Documentation

    * link:None[Put firewalld documentation in here]

[discrete]
== End of Unit

link:../RHEL8-Workshop.adoc#toc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////

