:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Firewalld - Firewall Service Management

The *firewalld* daemon provides a dynamically managed firewall for enhanced network security.  The firewalld daemon is control by way of a command-line tool `firewall-cmd` or a gui tool provided by the `firewall-config` rpm package. For today's workshop, you will focus strictly on the command line interface.

Features of firewalld include:

  * support for IPv4 and IPv6 settings
  * support for ethernet bridges
  * support for network “zones” which assigns level of trust to a network / connections / interfaces
  * separation of runtime and permanent configuration options
  * interface for external services to manage firewall rules directly

== Getting Started

Starting on the host *workstation.example.com*, let's ssh over to *node2.example.com*.  No password should be required.

.[root@workstation]#
----
ssh node1.example.com
----

Verify that you are on the right host for these exercises.

.[root@node3]#
----
cheat-firewalld-checkhost.sh
----

Now you are ready to begin

== Installation

Firewalld is already installed and running on you host. These steps provided here will restore firewalld if it has been disabled. It should NOT be necessary to run these commands in this lab.

[NOTE]
====
_Native command(s) to enable firewalld_
----
systemctl stop nftables
systemctl disable nftables
yum install firewalld
systemctl enable --now firewalld 
systemctl status -l firewalld 
----
====

== Configuration

Firewalld uses several different, completely adaptable, XML config files to store configurations. These files also ensure run-time and persistent configuration separation. 

The configuration files are stored in 
  * /usr/lib/firewalld
  * /etc/firewalld
  
Red Hat distributes the default servicee configurations in /usr/lib/firewalld.  These configuations are NOT meant for customization.  They WILL be overwritten and replaced from time to time as Red Hat releases new packages or updates for the operating system.

Customizations for firewall configuration belowing in */etc/filrewalld*.  These configuration files (if they exist) take precedence over the default configs.

=== Zone Configs

Firewald uses zones to assign a level of trust to a network and its associated connections and interfaces. The zone files include definitions of Services, Ports (ranges) with protocols, Rich rules, Internet Control Message Protocol (ICMP) blocks , Masquerading and Port/packet forwarding. There are several built-in zones: block, dmz, drop, external, home, internal, public, trusted, work - and you can also create new zones 

Each zone is similar to a complete firewall and there is a single zone selection per environment or connection. The public zone is the Initial default. Zones are identified in ifcfg files or NetworkManager configuration using: ZONE=<name> 

Let us examine a couple of the system's default zone files in */usr/lib/firewalld/zones*

.public.xml
[source,indent=4]
----
<?xml version="1.0" encoding="utf-8"?> 
<zone>
	<service name="ssh"/>
	<service name="dhcpv6-client"/>
</zone>
----

.drop.xml
[source,indent=4]
----
<?xml version="1.0" encoding="utf-8"?>
<zone target="DROP">
  <short>Drop</short>
  <description>Unsolicited incoming network packets are dropped. Incoming packets that are related to outgoing network connections are accepted. Outgoing network connections are allowed.</description>
</zone>
----

=== Service Configs

There are nearly 50 built-in services files shipped with firewalld. Services files include Port (ranges) with protocol, Netfilter helper modules, and destination address (range) for IPv4 and/or IPv6. You can also create your own services files or customize the default files. To customize a file, simply copy it from /usr/lib/firewalld/services to /etc/firewalld/services then make any required changes. 

Here are a couple common configs for services defined in */usr/lib/firewalld/services *.

.http.xml
[source,indent=4]
----
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>SSH</short>
  <description>Secure Shell (SSH) is a protocol for logging into and executing commands on remote machines. It provides secure encrypted communications. If you plan on accessing your machine remotely via SSH over a firewalled interface, enable this option. You need the openssh-server package installed for this option to be useful.</description>
  <port protocol="tcp" port="22"/>
</service>
----

.http.xml
[source,indent=4]
----
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>WWW (HTTP)</short>
  <description>HTTP is the protocol used to serve Web pages. If you plan to make your Web server publicly available, enable this option. This option is not required for viewing pages locally or developing Web pages.</description>
  <port protocol="tcp" port="80"/>
</service>
----

== Firewall Basics

.[root@node1]#
----
firewall-cmd --state
----

.Command Output
[source,indent=4]
----
running
----

.[root@node1]#
----
firewall-cmd --get-active-zones
----

.Command Output
[source,indent=4]
----
libvirt
  interfaces: virbr0
public
  interfaces: ens3
----

.[root@node1]#
----
firewall-cmd --zone=public --list-interfaces
----

.Command Output
[source,indent=4]
----
ens3
----

.[root@node1]#
----
firewall-cmd --zone=public --list-services
----

.Command Output
[source,indent=4]
----
cockpit dhcpv6-client ssh
----

.[root@node1]#
----
firewall-cmd --info-service=cockpit
----

.Command Output
[source,indent=4]
----
cockpit
  ports: 9090/tcp
  protocols:
  source-ports:
  modules:
  destination:
----

.[root@node1]#
----
firewall-cmd --zone=public --list-all
----

.Command Output
[source,indent=4]
----
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: ens3
  sources:
  services: cockpit dhcpv6-client ssh
  ports: 443/tcp
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
----




== Managing Default Services

Default Services are those that are pre-defined by configuration files in either */etc/firewalld* or */usr/lib/firewalld*.  This would include any configs delivered by Red Hat as part of the operating system or those added by a system administer.

Here we will take a moment to enable the http and https service ports.

=== Add a Default Service

.[root@node1]#
----
firewall-cmd --add-service=http --add-service=https
----

.Command Output
[source,indent=4]
----
success
----

.[root@node1]#
----
firewall-cmd --list-services
----

.Command Output
[source,indent=4]
----
cockpit dhcpv6-client http https ssh
----

.[root@node1]#
----
firewall-cmd --list-services --permanent
----

.Command Output
[source,indent=4]
----
cockpit dhcpv6-client ssh
----

.[root@node1]#
----
firewall-cmd --runtime-to-permanent
----

NOTE: you could have also passed the *--permanent* flag to the original call the *--add-service*

.[root@node1]#
----
firewall-cmd --list-services --permanent
----

.Command Output
[source,indent=4]
----
cockpit dhcpv6-client http https ssh
----

== Delete a Default Service

Now let us disable a service port not needed for our workshop environment.

.[root@node1]#
----
firewall-cmd --permanent --delete-service=dhcpv6-client
----

.Command Output
[source,indent=4]
----
----

.[root@node1]#
----
firewall-cmd --list-services --permanent
----


== Managing Custom Services

=== Add Custom Service

----
firewall-cmd --add-port=8080/tcp --add-port=8443/tcp --permanent
----

=== Delete Custome Service

.[root@node1]#
----
firewall-cmd --delete-port=8080/tcp --delete-port=8443/tcp --permanent
----

== Create a Custom Service Config

=== Install Configuration File


=== Reload firewalld Daemon


=== Enable Custom Service


=== Delete Custom Service



== Panic Mode

----
firewall-cmd --query-panic
----

[NOTE]
====
_DO NOT RUN THESE COMMANDS_
----
firewall-cmd --panic-on 

firewall-cmd --panic-off
----
====


== Additional Resources

Red Hat Documentation

    * link:None[Put firewalld documentation in here]

    * link:https://developers.redhat.com/blog/2018/08/10/firewalld-the-future-is-nftables/[Firewalld: The Future is nftables]
    
[discrete]
== End of Unit

link:../RHEL8-Workshop.adoc#toc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////

