:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


= Firewalld - Dynamic DYNAMIC FIREWALL

.[root@workstation]#
----
ssh node1.example.com
----

Describe the expected output if necessary

.Command Output
[source,indent=4]
----
Output from previous command
----

The *firewalld* daemon provides a dynamically managed firewall with support for network “zones” to assign a level of trust to a network and its associated connections and interfaces. It has support for IPv4 and IPv6 firewall settings. It supports Ethernet bridges and has a separation of runtime and permanent configuration options. It also has an interface for services or applications to add firewall rules directly.

The *nftables* service stores configuration in /etc/sysconfig/fstables while firewalld stores it in various XML files in /usr/lib/firewalld/ and /etc/firewalld/.

Note: The /etc/sysconfig/nfstables file does not exist as firewalld is installed by default on Red Hat Enterprise Linux.

Both firewalld and nftables tools use nfstables to talk to the kernel packet filter. Administrators should pick one tool as they will interfere with one another is used simultaneously.  Do not use them both.

Note: Making use of the systemctl mask command will ensure that only one or the other service may be started, even if both are available on the system.

== Getting Started

Get started
1. Log into workstation VM as root.

2. firewalld is already installed and running on RHEL7. These steps will restore firewalld if it has been disabled. The below steps are not necessary to run in this lab 

#	systemctl stop iptables ip6tables 
#	systemctl disable iptables ip6tables 
#	yum install firewalld firewall-config 
#	systemctl enable firewalld 
#	systemctl start firewalld 
#	systemctl status -l firewalld 

3. firewalld uses several different, completely adaptable, XML config files to store configurations. These files also ensure run-time and persistent configuration separation. The default configuration files are in /usr/lib/firewalld, while user customized files (which take precedence if they exist) are in /etc/firewalld. 

Examine the default files - both the zones and services files 

# cd /usr/lib/firewalld/zones 
# cd /usr/lib/firewalld/services 


4. firewald uses zones to assign a level of trust to a network and its associated connections and interfaces. The zone files include definitions of Services, Ports (ranges) with protocols, Rich rules, Internet Control Message Protocol (ICMP) blocks , Masquerading and Port/packet forwarding. There are several built-in zones: block, dmz, drop, external, home, internal, public, trusted, work - and you can also create new zones 

Each zone is similar to a complete firewall and there is a single zone selection per environment or connection. The public zone is the Initial default. Zones are identified in ifcfg files or NetworkManager configuration using: ZONE=<name> 

Here is an example of the public zone file from /usr/lib/firewalld/zones

public
<?xml version="1.0" encoding="utf-8"?> 
<zone>
	<service name="ssh"/>
	<service name="dhcpv6-client"/>
</zone>

drop

<?xml version="1.0" encoding="utf-8"?> <zone target=”DROP”>
</zone>

custom
<?xml version="1.0" encoding="utf-8"?> 
<zone>
	<interface name="em2"/> 
<source address="10.0.1.0/24"/> 
<service name="ssh"/>
	<service name="ipp-client"/> 
<service name="dhcpv6-client"/>
	<rule><protocol value="ah"/><accept/></rule>
</zone>

5. There are nearly 50 built-in services files shipped with firewalld. Services files include Port (ranges) with protocol, Netfilter helper modules, and destination address (range) for IPv4 and/or IPv6. You can also create your own services files or customize the default files. To customize a file, simply copy it from /usr/lib/firewalld/services to /etc/firewalld/services then make any required changes. 

Here is an example of the default http.xml services file from /usr/lib/firewalld/services 

<?xml version="1.0" encoding="utf-8"?> 
<service>
	<short>WWW (HTTP)</short>
<description>HTTP is the protocol used to serve Web pages. If you plan to make your Web server publicly available, enable this option. This option is not required for viewing pages locally or developing Web pages.</description>
	<port protocol="tcp" port="80"/> 
</service>





























== Additional Resources

Red Hat Documentation

    * link:https://https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8-beta/html/installing_identity_management_and_access_control/deploying-session-recording[Deplying Session Recording on Red Hat Enterprise Linux]

[discrete]
== End of Unit

link:../RHEL8-Workshop.adoc#toc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////

