:guid: %guid%
:ssh_command: %ssh_command%
:ssh_password: %ssh_password%
:ssh_username: %ssh_username%
:targethost_fqdn: %targethost%
:markup-in-source: verbatim,attributes,quotes
:show_solution: true

== GUID Information

[bash,options="nowrap",subs="{markup-in-source}"]
----
Your GUID is: *{guid}*
----

== SSH Information

  * Target host is: *{targethost_fqdn}*

  * Username is: *{ssh_username}*

  * Password is: *{ssh_password}*

== Workshop Setup

Connecting to the bastion host via ssh:

[source,options="nowrap",subs="{markup-in-source}",role="execute"]
----
*{ssh_command} -o "StrictHostKeyChecking no"*
----

Send the password:

[source,options="nowrap",subs="{markup-in-source}",role="execute"]
----
*{ssh_password}*
----

Escalate your priviledges with 'sudo':

[source,options="nowrap",subs="{markup-in-source}",role="execute"]
----
*sudo -i*
----

Execute the workshop setup script:

[source,options="nowrap",subs="{markup-in-source}",role="execute"]
----
*cd ~/RHEL8-Workshop; ./rhel8-workshop.sh all*
----

Set back for a short presentation, this should take about 8 minutes.


== Environment Description

WARNING: As an administrator, you are capable of ruining your environment.  We strongly encourage you 
to stick to the exercises as prescribed.  Recovery of your environment is unlikely due to limited time and resources.

NOTE: We only test with Firefox and/or Google Chrome.  Your mileage will vary using MacOS Safari or Windows Explorer.

Exercises in this workshop require either:

  * shell access (via ssh)
  * shell access (via bookbag)
  * web gui access (via web console)

You can use the convenient shell provided to the right of these instructions (bookbag), or if you prefer you can use your preferred ssh client with the same connectivity info.  Your choice...

Activities in this workshop are performed on virtual machines running in a public cloud.  Each attendee has received their own unique environment and will be provided administrator priviledges when needed.

There are 4 systems:

  * bastion - primary system and launch point to other hosts
  * node1
  * node2
  * node3
  * node4

The network domain is likely `example.com` but not necessarily so.  We expect most exercises and envionments will work by using the short hostnames.  So when asked to use `node1` for a unit:

  * ssh to `bastion` using the provided connection info 
  * and then `ssh node1`

