:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Getting Started

[discrete]
== Additional Reference Materials

NOTE: You are not required to reference outside documentation for these exercises.  This is informational only.

Red Hat's official documentation can be found publicly with the links provided below.  It is important to note that this workshop guide supports a very narrowly scoped and simple installation of the Openshift Container Platform (OCP).  Please refer to the official Red Hat documentation for complete information on the installation procedures.

    * link:https://access.redhat.com/documentation/[RHEL 8 Documentation TBD]

Now let us proceed with getting your environment ready for work.

== Preparing for Installation

=== Sign-On on to your *workstation* session

Using the connection information and credentials provided by the instructor, get yourselves signed into your workstation session.

=== Become the root user

In order to execute the environment preparation, we need to become the administrative user 'root'.

.[student@workstation ~]$ 
----
sudo -i
----

=== Enable 'screen' Terminal Session

Again, if you haven't already we strongly encourage the use of the `screen` utility.
    
.[student@workstation ~]$ 
----
screen -m
----

For more tips on using screen have a look in the link:./Preface.adoc[Workshop Preface]

=== Download the Workshop project from GitHub

.[root@workstation ~]#
----
cd ~
    
git clone https://github.com/xtophd/RHEL8-Workshop
----

== RHEL 8 Workshop Set Up

=== Run the Prep Script

WARNING: It is important to be in the correct working directory for these installation procedures to function properly.  

.[root@workstation ~]#
----
cd ~/RHEL8-Workshop
----

.[root@workstation ~]#
----
bash prepare-install-openshift.sh
----

If you examine the install script, it breaks the installation into 3 parts: pre-install, install & post-install.  Let us briefly review what each phase contributes to the installation process.

==== Openshift Pre-Installation

The pre-installation performs 2 primary activities:

* Workstation Actions
** minimum package installation

* OCP Cluster Node Actions
** reconfigure docker storage to use a block device
** enable and start firewalld
** minimum package installation

==== Openshift Installation

This portion excutes the official Openshift Installer playbook.  

==== Openshift Post-Installation

The post-install has very little to do with openshift itself.  The post-install deploys various configuration files and scripts which are used during the workshop exercises.  Additionally, the post-install configures NFS storage host for use as a persistent volume.  More on that topic later.

Again, there are 2 primary activities:

* Workstation Actions
** deploys sample files used by exercises
** configures, enables and starts NFS services
** cleans up yum content

* OCP Cluster Node Actions
** deploys sample files used by exercises
** deletes and deploys OCP router with replicas=2
** cleans up yum content (frees disk space)

=== A Few Words While the Installer Runs

So you might be asking yourself, *why* another workshop?  What's different about this one?

I have 2 simple goals:

. Explain what the Red Hat Openshift Container Platform is via a hands-on approach
. Deliver an "Ah-Ha" moment for each participant regarding containerized workloads:
** What's in it for operators
** What's in it for developers

So while the OCP installer runs for the next 30 minutes, your presenter (perhaps there is a sponsor?) may opt to provide a brief discussion on a related topic.  Valuable themes include _(in the future I hope to provide links to brief documents on the topics below)_:

* "An Introduction to Openshift"
* "Modern Application Development"
* "Architectural Overview of this Workshop"
* or merely host a simple Q&A session

In any case, use this time to set some foundational knowledge.

== Conclusion

The installation of Red Hat Openshift Container Platform is now complete and you should be ready to begin with the exercises.  A couple of remaining words of advice:

1.  Some exercises are dependant on the successful completion of other exericses.  Those dependencies will be noted at the top of each unit.
2.  Pay attention to which linux login to use
3.  Pay attention to which ocp user to use
4.  Also be sure to pay close attention to which host you are executing tasks from


[discrete]
== End of Unit

*Next:* link:Docker-Fundamentals.adoc[Docker: Fundamentals]

OR

*Next:* link:CLI-First-Time-Login.adoc[OCP CLI: First Time Login]

link:../OCP-Workshop.adoc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
