:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Getting Started

[discrete]
== Additional Reference Materials

NOTE: You are not required to reference outside documentation for these exercises.  This is informational only.

Red Hat's official documentation can be found publicly with the links provided below.  Please refer to the official Red Hat documentation for complete information.

    * link:https://https//access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8-beta/[RHEL 8 Documentation TBD]

Now let us proceed with getting your environment ready for work.

== Preparing for Installation

=== Sign-On on to your *workstation* session

Using the connection information and credentials provided by the instructor, get yourselves signed into your workstation session.

=== Become the root user

In order to execute the environment preparation, we need to become the administrative user 'root'.

.[student@workstation ~]$ 
----
sudo -i
----

=== Enable 'tmux' Terminal Session

Again, if you haven't already we strongly encourage the use of the `tmux` utility.
    
.[student@workstation ~]$ 
----
tmux
----

=== Download the Workshop project from GitHub

.[root@workstation ~]#
----
cd ~
    
git clone https://github.com/xtophd/RHEL8-Workshop
----

== RHEL 8 Workshop Set Up

=== Run the Prep Script

WARNING: It is important to be in the correct working directory for these installation procedures to function properly.  

.[root@workstation ~]#
----
cd ~/RHEL8-Workshop
----

.[root@workstation ~]#
----
bash prepare-rhel8-workshop.sh
----

=== A Few Words While the Installer Runs

Put something clever here :-)

== Conclusion

The set up of the RHEL 8 Workshop should now be complete.  A couple of remaining words of advice:

1.  Some exercises are dependant on the successful completion of other exericses.  Those dependencies will be noted.
2.  Pay attention to which linux login to use
3.  Pay attention to which host to use
4.  There is an exam at the conclusion of the workshop... #notreally

[discrete]
== End of Unit

link:../RHEL8-Workshop.adoc#toc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
