:sectnums:
:sectnumlevels: 3
:markup-in-source: verbatim,attributes,quotes
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:toc:
:toclevels: 1

= Pbench Agent Fundamentals

== Overview

In this unit, we will get familiar with the Pbench Agent, the CLI it provides, and the available containers offered.  

== Getting Started

!!!! FIXME: ensure quay.io is one of the default containers in the registry

For these exercises, you will be using the host `node1` as user `root`, and hosts `node2` and `node3` as user `cloud-user`.

From host `workstation`, ssh to `node1`.

[bash,options="nowrap",subs="{markup-in-source}"]
----
$ *ssh node1*
----

Use `sudo` to elevate your priviledges.

[bash,options="nowrap",subs="{markup-in-source}"]
----
$ *sudo -i*
----

Verify that you are on the right host for these exercises.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *cheat-pbench-checkhost.sh*
----

You are now ready to proceed with these exercises.

== Pbench Agent Basics

----
# Get pbench-agent installed on node1 as root
# yum install pbench-agent 
----

Then have them go to node2 and node3, and install there as well.

# Define our own tool set

!!!! FIXME: Edit pbench-agent.cfg to add our own toolset
vmstat turbostat sar pcp node-exporter


!!!! FIXME: talk about pcp and node-exporter "persistent" tools

!!!! FIXME: show how multiple user-benchmark iterations work to highlight the transient tools vs persistent tools


As root, lets run a simple workload, and what data is collected
----
# pbench-register-tool-set
# pbench-register-tool --name=vmstat --remote=node2
# pbench-register-tool --name=disk   --remote=node3
# pbench-user-benchmark --config=first-run -- sine-wave <arguments>
----

GOAL: to them a chance to inspect what data is collected in /var/lib/pbench-agent
 * Show them where the registered tools are
 * Show them where the log file is
 * Show where the data is collected
 
Point out that:
 * some tools require root (default toolset has "turbostat" and "perf" (really "perf record"))
 * and tool data collection is configured in /opt/pbench-agent/config/pbench-agent.cfg by default to be /var/lib/pbench-agent, which is owned by root


== Container Pbench Agent

1. Undo the pbench-agent installs on node1, node2, and node3
----
# for n in {1..3}; do ssh node${n} yum remove -y pbench-agent; done
----

Do this to prove non-root working use case.

2. Move to workstation

as root install pbench-agent on workstation

----
# yum install pbench-agent
----

3. Logout of root

4. verify you are now "cloud-user" on workstation

!!!!  Figure out where our Redis Server will be

5. setup non-root pbench environment variables
    defines our local data directory

----
$ mkdir some-directory
$ export pbench_run=<some directory>
$ export _PBENCH_TOOL_MEISTER_CLIENT_LOG_LEVEL=debug
$ export _PBENCH_TOOL_MEISTER_START_LOG_LEVEL=debug
$ export _PBENCH_TOOL_MEISTER_STOP_LOG_LEVEL=debug
----
    
6. register tools

----
for n in {1..3}; do
    echo node${i}
done > ${pbench_run}/remotes.lis

# Register the default tool set, will be recorded in
# ${pbench_run}/tools-v1-default
for tool in vmstat turbostat sar pcp node-exporter; do
    printf -- "\npbench-register-tool --name=${tool} --remotes=@${pbench_run}/remotes.lis\n"
    pbench-register-tool --name=${tool} --remotes=@${pbench_run}/remotes.lis
    sleep 1
done
----

7. Start tool meisters

!!!! FIXME: provide TAG environment variable default

---
while read node; do
    echo "${node}: podman run --name pbench-agent-tool-meister ..."
    ssh ${node} podman run \
        --name pbench-agent-tool-meister \
        --network host \
        --ulimit nofile=65536:65536 \
        --rm \
        -d \
        -e REDIS_HOST=${REDIS_HOST} \
        -e REDIS_PORT=${REDIS_PORT} \
        -e PARAM_KEY=tm-default-${node} \
        -e _PBENCH_TOOL_MEISTER_LOG_LEVEL=debug \
        quay.io/pbench/pbench-agent-tool-meister-${DISTRO}:${TAG}
done < ${pbench_run}/remotes.lis
----

8. Start tool data sink on the ** workstation **

----
$ podman run --name pbench-agent-tool-data-sink --network host --volume ${pbench_run}:/var/lib/pbench-agent:Z --ulimit nofile=65536:65536 --rm -d -e REDIS_HOST=${REDIS_HOST} -e REDIS_PORT=${REDIS_PORT} -e PARAM_KEY=tds-default -e _PBENCH_TOOL_DATA_SINK_LOG_LEVEL=debug quay.io/pbench/pbench-agent-tool-data-sink-${DISTRO}:${TAG}
----

----
$ # FIXME should we run this on node3 or something?
$ podman run --name demo-tm-redis --network host --rm -d redis
$ export PBENCH_REDIS_SERVER=workstation:6543
----

!!!! FIXME: put the above commands into a script


AT this point, the "tool meister" orchestration is done; no actions have been taken, no data collected, etc.


9. All we do is run workload

The +PBENCH_REDIS_SERVER+ environment directs the pbench-user-benchmark command to use the existing Tool Meister orchestration we have performed.

----
$ pbench-user-benchmark --config=second-run -- sleep 30
----

!!!! FIXME: walk them through inspecting the data collected

Where is your data?



STRETCH GOAL: run redis server on one of the nodes instead
STRETCH GOAL: run the tool data sink on one of the nodes
STRETCH GOAL: run a tool meister on the workstation




== Visualizing Live Prometheus/PCP metrics

Let's see how we can visualize live metrics in Grafana for PCP and pbench.

Run above setup again

!!!! FIXME: run orchestration script

----
$ pbench-user-benchmark --config=second-run -- sleep 300
----

Run the live metrics container

----
$ podman run --network host -d --rm --name pbench-live-viz quay.io/pbench/live-metric-visualizer
----

Open a browser to watch live metrics at: http://workstation:3000/.

!!!! FIXME: get Mustafa to describe what to do...
How to log in: admin/admin; select the tab for dashboards, etc.

!!!! FIXME: add cheat scrip to pull all referenced images

Instructions for use:
Open a web browser, and go to hostname:3000 (or localhost:3000)
Default username: admin, default password: admin


== Visualizing Live Prometheus/PCP metrics

Visualizing previous captured metrics for PCP and pbench

!!!! FIXME: get the right incantation


Where we direct the use of a previous run to visualize.

Navigate to <run-dir>/tools-default and extract the pcp data from the collected tarball

----
$ podman run --network host -d --rm --name pbench-pcp-viz --volume ${pbench_run}/${run_name}/tools-default/pcp/data:/var/log/pcp/pmlogger:Z pbench/pcp-graf-visualizer
$ podman run --network host -d --rm --name pbench-prom-viz --volume ${pbench_run}:/var/lib/pbench-agent quay.io/pbench/prom-graf-visualizer
----

Open a web browser, and go to hostname:3000 (or localhost:3000)
Default username: admin, default password: admin


== Stretch GOAL: pbench-uperf for pbench-fio workload

STRETCH GOAL: run a uperf or fio workload

[discrete]
== Additional Reference Materials

    * link:https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image[Introducing the Red Hat Universal Base Image - Scott McCarty]
    * link:https://developers.redhat.com/blog/2019/04/25/podman-basics-cheat-sheet/[Podman Basics Cheat Sheet - Doug Tidwell]
    * link:https://developers.redhat.com/blog/2018/11/20/buildah-podman-containers-without-daemons/[Containers without daemons: Podman and Buildah available in RHEL 7.6 and RHEL 8 Beta - Tom Sweeney]

[discrete]
== End of Unit

ifdef::env-github[]
link:../RHEL8-Workshop.adoc#toc[Return to TOC]
endif::[]

////
Always end files with a blank line to avoid include problems.
////
