:sectnums:
:sectnumlevels: 3
:markup-in-source: verbatim,attributes,quotes
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


:toc:
:toclevels: 1

= Stratis : Storage Management Made Easy

== Overview

WARNING: Stratis is considered *Technology Preview* and is not intended for production use.  For information on Red Hat scope of support for Technology Preview features, see: link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope]

Stratis is a command-line tool to create, modify, and destroy Stratis pools, and the filesystems allocated from the pool.  Stratis creates a pool from one or more block devices (blockdevs), and then enables multiple filesystems to be created from the pool.

Instead of an entirely in-kernel approach like ZFS or Btrfs, Stratis uses a hybrid user/kernel approach that builds upon existing block capabilities like device-mapper, existing filesystem capabilities like XFS, and a user space daemon for monitoring and control.

== Getting Started

For these exercises, you will be using the host `node2` as user `root`.

From host `workstation`, ssh to `node2`.

[bash,options="nowrap",subs="{markup-in-source}"]
----
$ *ssh node2*
----

Use `sudo` to elevate your priviledges.

[bash,options="nowrap",subs="{markup-in-source}"]
----
$ *sudo -i*
----

Verify that you are on the right host for these exercises.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *cheat-stratis-checkhost.sh*
----

You are now ready to proceed with these exercises.

== Installation & Configuration

Install the required packages - this will pull in several Python related dependencies.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *yum install -y stratisd stratis-cli*
----

Next we need to enable the `stratisd` service

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *systemctl enable --now stratisd*
----

NOTE: The "enable --now" syntax is new in RHEL 8.  It allows for permanently enabling as well as immediately starting services in a single command.

Finally check the service status.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *systemctl status stratisd*

● stratisd.service - A daemon that manages a pool of block devices to create flexible file systems
   Loaded: loaded (/usr/lib/systemd/system/stratisd.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-04-27 18:41:52 EDT; 10s ago
 	Docs: man:stratisd(8)
 Main PID: 9562 (stratisd)
	Tasks: 1 (limit: 24006)
   Memory: 940.0K
   CGroup: /system.slice/stratisd.service
       	└─9562 /usr/libexec/stratisd --debug

Apr 27 18:41:52 node2.example.com systemd[1]: Started A daemon that manages a pool of block devices to create flexible file systems.
----

== Create Storage Pool

WARNING: /dev/vda is the system disk, DO NOT use it in any of the stratis commands or the vm will become unusable.

Next, see what disks/block devices are present, create a pool, create a filesystem in the pool, and mount the filesystem.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *sfdisk -s*

/dev/vda:  31457280
/dev/vdb:   5242880
/dev/vdc:   5242880
/dev/vdd:   5242880
/dev/vde:   5242880
total: 52428800 blocks
----

WARNING: REMEMBER - DON'T USE /dev/vda!!!

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *stratis pool create summitpool /dev/vdb /dev/vdc*
----

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *stratis pool list*

Name      	Total Physical Size  Total Physical Used
summitpool                 10 GiB               56 MiB
----

Check the status of the block devices

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *stratis blockdev list*

Pool Name   Device Node     Physical Size   State  Tier
summitpool  /dev/vdb                5 GiB  In-use  Data
summitpool  /dev/vdc                5 GiB  In-use  Data
----

== Create Filesystem

Now create a filesystem, a directory mount point, and mount the filesystem:
(note that “fs” can optionally be written out as “filesystem”)

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *stratis fs create summitpool summitfs*
----

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *stratis fs list*

Pool Name   Name      Used     Created            Device                        UUID
summitpool  summitfs  546 MiB  Apr 18 2020 09:15  /stratis/summitpool/summitfs  095fb4891a5743d0a589217071ff71dc
----

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *mkdir /summitdir*
# *mount /stratis/summitpool/summitfs /summitdir*
# *df -h*

Filesystem                                 Size  Used Avail Use% Mounted on
devtmpfs                                   1.9G     0  1.9G   0% /dev
tmpfs                                      1.9G     0  1.9G   0% /dev/shm
tmpfs                                      1.9G   17M  1.9G   1% /run
tmpfs                                      1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/vda1                                  30G  2.4G   28G   8% /
tmpfs                                      379M     0  379M   0% /run/user/1000
/dev/mapper/stratis-1-3e8e[_truncated_]71dc  1.0T  7.2G 1017G   1% /summitdir
----

The actual space used by a filesystem can be shown using the `stratis fs list` command as shown above.  Notice how the summitdir filesystem has a virtual size of 1T.  If the data in a filesystem actually approaches its virtual size, Stratis will automatically grow the filesystem.

== Create Mount Point

Now make sure the filesystem will mount at boot time by adding the following line to the end of the /etc/fstab file:

INFO: If you are comfortable with an editor, you can type it in or cut and paste using the UUID from the output of “stratis fs”.   If not, you can use a cheat-script we prepared for you.

./etc/fstab
[source,options="nowrap",subs="{markup-in-source}"]
----
UUID=<the-uuid-unique-to-the-new-filesystem>  /summitdir  xfs  defaults  0  0
----

[bash,options="nowrap",subs="{markup-in-source}"]
----
cheat-stratis-fstab.sh
----

[NOTE]
====
_Native command(s) to amend /etc/fstab_
----
UUID=`lsblk -n -o uuid /stratis/summitpool/summitfs`
echo "UUID=${UUID} /summitdir xfs defaults 0 0" >> /etc/fstab
----
====

Verify that the /etc/fstab entry is correct by unmounting and mounting the filesystem one last time.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *umount /summitdir*
# *mount /summitdir*
# *df -h*

Filesystem                                 Size  Used Avail Use% Mounted on
devtmpfs                                   1.9G     0  1.9G   0% /dev
tmpfs                                      1.9G     0  1.9G   0% /dev/shm
tmpfs                                      1.9G   17M  1.9G   1% /run
tmpfs                                      1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/vda1                                  30G  2.4G   28G   8% /
tmpfs                                      379M     0  379M   0% /run/user/1000
/dev/mapper/stratis-1-3e8e[_truncated_]71dc  1.0T  7.2G 1017G   1% /summitdir
----

== Add Cache Device

Stratis also makes it easy to add cache devices.  For example, say the filesystem we just created runs into some I/O performance issues.  You bought an SSD (solid state disk) and need to configure it into the system to act as a high speed cache.  Use the following commands to add the drive (/dev/vdd) and check its status:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *stratis pool add-cache summitpool  /dev/vdd*
----

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *stratis blockdev*

Pool Name	Device Node    Physical Size   State   Tier
summitpool   /dev/vdb                5 GiB  In-use   Data
summitpool   /dev/vdc                5 GiB  In-use   Data
summitpool   /dev/vdd                5 GiB  In-use  Cache
----

== Grow Storage Pool

Finally, Stratis also makes it easy to add space to a pool.  Suppose the “summitfs” filesystem is growing close to the physical space in “summitpool”, adding an additional disk/block device is done using:

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *stratis pool add-data summitpool /dev/vde*
----

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *stratis blockdev*

Pool Name    Device Node    Physical Size   State   Tier
summitpool   /dev/vdb               5 GiB  In-use   Data
summitpool   /dev/vdc               5 GiB  In-use   Data
summitpool   /dev/vdd               5 GiB  In-use  Cache
summitpool   /dev/vde               5 GiB  In-use   Data
----

Verify that the pool shows the additional space, and that the amount used is now in a safe range.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *stratis pool*

Name          Total Physical Size   Total Physical Used
summitpool                 15 GiB               606 MiB
----

== Additional Resources

Red Hat Documentation

    * link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/managing-layered-local-storage-with-stratis_managing-file-systems[Managing Layered Local Storage with Stratis]

[discrete]
== End of Unit

ifdef::env-github[]
link:../RHEL8-Workshop.adoc#toc[Return to TOC]
endif::[]

////
Always end files with a blank line to avoid include problems.
////


