:sectnums:
:sectnumlevels: 3
:markup-in-source: verbatim,attributes,quotes
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:toc:
:toclevels: 1

= Session Recording with Tlog

== Overview

Tlog is a terminal I/O recording and playback package for Linux.  The session logs retain all the passed data and timing.  Sessions are recorded in JSON format as to eventually deliver the data to a storage service _(such as Elasticsearch)_ where it can be searched, queried and be played back.

If you have successfully run the RHEL 8 lab preparation playbook, then node1.example.com has already been properly configured for session logging.  What follows are some basic exercises to demonstrate how this facility functions.

== Getting Started

For these exercises, you will be using the host `node1` as user `root`.

From host `workstation`, ssh to `node1`.

[bash,options="nowrap",subs="{markup-in-source}"]
----
$ *ssh node1*
----

Use `sudo` to elevate your priviledges.

[bash,options="nowrap",subs="{markup-in-source}"]
----
$ *sudo -i*
----

Verify that you are on the right host for these exercises.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *cheat-tlog-checkhost.sh*
----

You are now ready to proceed with these exercises.

== Creating a Session Log

The system has been configured with an additional non-priviledged user called `other-user`.  Run the following command to change to the `other-user`.

NOTE: The command is 'su' + 'dash' + 'other-user'.  Don't forget the dash!

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *su - other-user*

ATTENTION! Your session is being recorded!
----

You should have gotten a message when connecting to node1 that the session is being recorded.

Now to do a few activities worth logging.  You can check out a directory listing, look at the host's _passwd_ and _shadow_ files.  

[bash,options="nowrap",subs="{markup-in-source}"]
----
$ *ls -l /etc*
----

[bash,options="nowrap",subs="{markup-in-source}"]
----
$ *cat /etc/passwd*
----

[bash,options="nowrap",subs="{markup-in-source}"]
----
$ *cat /etc/shadow*
----

Oh wait, you need root priviledges to see the contents of _/etc/shadow_.  You can use sudo for that!

[bash,options="nowrap",subs="{markup-in-source}"]
----
$ *sudo cat /etc/shadow*
----

We are done with our limited nafarious activities, so proceed to `exit`

[bash,options="nowrap",subs="{markup-in-source}"]
----
$ *exit*
----

== Session Play Back

Session logs are configured to record in the system journal by default.  A distinct advantage to this approach is that session recordings are also augmented with meta data which includes: user, session-id, host-id and a log-message-id.  Let's have a look.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *journalctl -o verbose  --output-fields=TLOG_USER,TLOG_REC TLOG_USER=cloud-user*

Sat 2019-04-27 21:21:27.852913 EDT [s=bcde42e4c96048c3908657177414e202;i=700;b=b2333248c22a4c5f912a>
    TLOG_USER=cloud-user
    TLOG_REC=b2333248c22a4c5f912a245f6266582e-3cb9-e9bf9
Sat 2019-04-27 21:21:33.354695 EDT [s=bcde42e4c96048c3908657177414e202;i=701;b=b2333248c22a4c5f912a>
    TLOG_USER=cloud-user
    TLOG_REC=b2333248c22a4c5f912a245f6266582e-3cb9-e9bf9
Sat 2019-04-27 21:21:43.483301 EDT [s=bcde42e4c96048c3908657177414e202;i=702;b=b2333248c22a4c5f912a>
    TLOG_USER=cloud-user
    TLOG_REC=b2333248c22a4c5f912a245f6266582e-3cb9-e9bf9
Sat 2019-04-27 21:21:54.193564 EDT [s=bcde42e4c96048c3908657177414e202;i=707;b=b2333248c22a4c5f912a>
    TLOG_USER=cloud-user
    TLOG_REC=b2333248c22a4c5f912a245f6266582e-3cb9-e9bf9
Sat 2019-04-27 21:21:58.770887 EDT [s=bcde42e4c96048c3908657177414e202;i=70c;b=b2333248c22a4c5f912a>
    TLOG_USER=cloud-user
    TLOG_REC=b2333248c22a4c5f912a245f6266582e-3cb9-e9bf9
----

Each one of those entries makes up a chunk of a session recording.  It is by way of searching the system journal and identifying the correct TLOG_REC for a specific session, that you can then play back the session using `tlog-play`.

We have taken the liberty of scripting this "search" to playback the last session log from the user cloud-user.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *cheat-tlog-playback.sh*
----

Once you hit enter on the above command, you will see a note that "Playback Started..." and again when "Playback Finished...".  Be patient until it completes and your root prompt returns.

[NOTE]
====
_Native command(s) to playback last tlog_
----
myTLOG=`journalctl -o verbose -n 1 --output-fields=TLOG_USER,TLOG_REC TLOG_USER=other-user | grep TLOG_REC`

tlog-play -r journal -M ${myTLOG}
----
====

== Initial Setup of TLOG

Clearly we have taken the liberty to pre-configure TLOG for this lab.  But, it was not very difficult.  TLOG requires a couple of packages, a configuration file and simple restart of the sssd service.

.[root@node1]#
----
yum install tlog cockpit-session-recording
----

Here is what the config file looks like _/etc/sssd/conf.d/sssd-session-recording.conf_

[source,indent=4]
----
# This file deployed by Ansible playbook
# /etc/sssd/conf.d/sssd-session-recording.conf

[session_recording]
scope = all
users = other-user
groups = other-user
----

And lastly, how to reload systemd and restart the service.

.[root@node1]#
----
systemctl daemon-reload
systemctl restart sssd
----

== Additional Resources

Red Hat Documentation

    * link:https://https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8-beta/html/installing_identity_management_and_access_control/deploying-session-recording[Deploying Session Recording on Red Hat Enterprise Linux]

[discrete]
== End of Unit

////
Always end files with a blank line to avoid include problems.
////

