:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


:toc:
:toclevels: 1

= Session Recording with Tlog

Tlog is a terminal I/O recording and playback package for Linux.  The session logs retain all the passed data and timing.  Sessions are recorded in JSON format as to eventually deliver the data to a storage service _(such as Elasticsearch)_ where it can be searched, queried and be played back.

If you have successfully run the RHEL 8 lab preparation playbook, then node1.example.com has already been properly configured for session logging.  What follows are some basic exercises to demonstrate how this facility functions.

== Creating a Session Log

Starting on the host *workstation.example.com*, let's ssh over to *node1.example.com*.  No password should be required.

.[root@workstation]#
----
ssh node1.example.com
----

Now change your effective userid to student using the `su` command.  Don't forget the dash, it's `su - student`.

.[root@node1]#
----
su - student
----

Notice the "ATTENTION" banner during your login.  Your session is being recorded!

.Your output should look like this
[source,indent=4]
----
# ---------------
#  Host FQDN : node1.example.com
# OS Version : RedHat 8.0
# ---------------
Last login: Sat Apr 27 19:55:02 2019 from 10.0.0.10

ATTENTION! Your session is being recorded!
----

Let us now do a few activities worth logging.  You can check out a directory listing, look at the host's _passwd_ and _shadow_ files.  
Oh wait, you need root priviledges to see the contents of _/etc/shadow_.  You can use sudo for that!  Now exit your shell.

.[student@node1]#
----
ls -l /etc

cat /etc/passwd

cat /etc/shadow

sudo cat /etc/shadow

exit
----

== Session Play Back

Session logs are configured to record in the system journal by default.  A distinct advantage to this approach is that session recordings are also augmented with meta data which includes: user, session-id, host-id and a log-message-id.  Let's have a look.

.[root@node1]#
----
journalctl -o verbose  --output-fields=TLOG_USER,TLOG_REC TLOG_USER=student
----

.You output should look like this
[source,indent=4]
----
Sat 2019-04-27 21:21:27.852913 EDT [s=bcde42e4c96048c3908657177414e202;i=700;b=b2333248c22a4c5f912a>
    TLOG_USER=student
    TLOG_REC=b2333248c22a4c5f912a245f6266582e-3cb9-e9bf9
Sat 2019-04-27 21:21:33.354695 EDT [s=bcde42e4c96048c3908657177414e202;i=701;b=b2333248c22a4c5f912a>
    TLOG_USER=student
    TLOG_REC=b2333248c22a4c5f912a245f6266582e-3cb9-e9bf9
Sat 2019-04-27 21:21:43.483301 EDT [s=bcde42e4c96048c3908657177414e202;i=702;b=b2333248c22a4c5f912a>
    TLOG_USER=student
    TLOG_REC=b2333248c22a4c5f912a245f6266582e-3cb9-e9bf9
Sat 2019-04-27 21:21:54.193564 EDT [s=bcde42e4c96048c3908657177414e202;i=707;b=b2333248c22a4c5f912a>
    TLOG_USER=student
    TLOG_REC=b2333248c22a4c5f912a245f6266582e-3cb9-e9bf9
Sat 2019-04-27 21:21:58.770887 EDT [s=bcde42e4c96048c3908657177414e202;i=70c;b=b2333248c22a4c5f912a>
    TLOG_USER=student
    TLOG_REC=b2333248c22a4c5f912a245f6266582e-3cb9-e9bf9
----

Each one of those entries makes up a chunk of a session recording.  It is by way of searching the system journal and identifying the correct TLOG_REC for a specific session, that you can then play back the session using `tlog-play`.

We have taken the liberty of scripting this "search" to playback the last session log from the user student.

.[root@node1]#
----
cheat-tlog-playback.sh
----

Once you hit enter on the above command, you will see a note that "Playback Started..." and again when "Playback Finished...".  Be patient until it completes and your root prompt returns.

[NOTE]
====
_Native command(s) to playback last tlog_
----
myTLOG=`journalctl -o verbose -n 1 --output-fields=TLOG_USER,TLOG_REC TLOG_USER=student | grep TLOG_REC`

tlog-play -r journal -M ${myTLOG}
----
====

== Initial Setup of TLOG

Clearly we have taken the liberty to pre-configure TLOG for this lab.  But, it was not very difficult.  TLOG requires a couple of packages, a configuration file and simple restart of the sssd service.

.[root@node1]#
----
yum install tlog cockpit-session-recording
----

Here is what the config file looks like _/etc/sssd/conf.d/sssd-session-recording.conf_

[source,indent=4]
----
# This file deployed by Ansible playbook
# /etc/sssd/conf.d/sssd-session-recording.conf

[session_recording]
scope = all
users = student
groups = student
----

And lastly, how to reload systemd and restart the service.

.[root@node1]#
----
systemctl daemon-reload
systemctl restart sssd
----

== Additional Resources

Red Hat Documentation

    * link:https://https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8-beta/html/installing_identity_management_and_access_control/deploying-session-recording[Deploying Session Recording on Red Hat Enterprise Linux]

[discrete]
== End of Unit

link:../RHEL8-Workshop.adoc#toc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////

