:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Session Recording with TLOG



== Creating a Session Log

Starting on the host *workstation.example.com*, let's ssh over to *node1.example.com*.  No password should be required.

.[root@workstation]#
----
ssh node1.example.com
----

Now change your effective userid to student using the `su` command.  Don't forget the dash, it's `su - student`.

.[root@workstation]#
----
su - student
----

Notice the "ATTENTION" banner during your login.  Your session is being recorded!

[source,indent=4]
----
# ---------------
#  Host FQDN : node1.example.com
# OS Version : RedHat 8.0
# ---------------
Last login: Sat Apr 27 19:55:02 2019 from 10.0.0.10

ATTENTION! Your session is being recorded!
----

Let us now do a few activities worth logging.  You can check out a directory listing, look at the host's _passwd_ and _shadow_ files.  
Oh wait, you need root priviledges to see the contents of _/etc/shadow_.  You can use sudo for that!  Now exit your shell.

.[root@node1]#
----
ls -l ~

cat /etc/passwd

cat /etc/shadow

sudo cat /etc/shadow

exit
----

== Session Play Back


== Initial Setup of TLOG

Clearly we have taken the liberty to pre-configure TLOG for this lab.  But, it was not very difficult.  TLOG requires a couple of packages, a configuration file and simple restart of the sssd service.

.[root@node1]#
----
yum install tlog cockpit-session-recording
----

Here is what the config file looks like _/etc/sssd/conf.d/sssd-session-recording.conf_
[source,indent=4]
----
# This file deployed by Ansible playbook
# /etc/sssd/conf.d/sssd-session-recording.conf

[session_recording]
scope = all
users = student
groups = student
----

And lastly, how to restart the service.

.[root@node1]#
----
yum install tlog cockpit-session-recording
----

== Additional Resources

Red Hat Documentation

    * link:https://https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8-beta/html/installing_identity_management_and_access_control/deploying-session-recording[DEPLOYING SESSION RECORDING ON RED HAT ENTERPRISE LINUX]

[discrete]
== End of Unit

link:../RHEL8-Workshop.adoc#toc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////


