:sectnums:
:sectnumlevels: 3
:markup-in-source: verbatim,attributes,quotes
:imagesdir: ./_images
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:toc:
:toclevels: 1

= Virtualization Management

NOTE: If you are using the web-console and do not see "Virtual Machines" in the menu, chances are that you need to sign-out and sign-in again.

Provided your hardware is reasonably modern, chances are that it supports virtualization.  This unit introduces simple virtualization management using kvm and libvirt.  You will learn how to:

    * Install additional necessary software
    * Enable necessary system services and firewall ports
    * Use the command line to create and manage a virtual machine
    * Use the web console (cockpit) to create and manage a virtual machine

== Getting Started

For these exercises, you will be using the host `bastion` as user `root`.

Use `sudo` to elevate your priviledges.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*sudo -i*
----

Verify that you are on the right host for these exercises.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*workshop-virt-checkhost.sh*
----

You are now ready to proceed with these exercises.

== Requirements

First we need to ensure the system being used supports either:

    * Intel VT-x and Intel 64 virtualization extensions
    * AMD-V and the AMD64 virtualization extensions

This is done with the following simple commands.

You can start by examining the CPU flags (capabilities) advertised by your system.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*grep -E 'svm|vmx' /proc/cpuinfo*
----

[source,options="nowrap",subs="{markup-in-source}"]
----
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 
clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good
nopl xtopology cpuid tsc_known_freq pni pclmulqdq *vmx* ssse3 fma cx16 pcid sse4_1 sse4_2 
x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnow
prefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept
vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rds
eed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 arat pku os
pke avx512_vnni md_clear arch_capabilities
----

You are looking for either the Intel flag (vmx) or the AMD flag (svm).  A more sophisticated command makes it a little easier to determine.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*if grep -qE 'svm|vmx' /proc/cpuinfo ; then echo "Virt Supported" ; else echo "WARNING!! Virt NOT Supported"; fi*
----

[source,options="nowrap",subs="{markup-in-source}"]
----
Virt Supported
----

After you install all the required software, there are some additional tools to provide more detailed reporting on system capabilities.

== Installation and Configuration

NOTE: Please note that all software has been pre-installed and configured.  These steps are provided as reference material only.

System needs to be configure with access to the following repos:

  * rhel-8-baseos-rpms
  * rhel-8-appstream-rpms

Install the required packages.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*yum install -y qemu-kvm libvirt virt-install libvirt-client libguestfs-tools cockpit-machines*
----

Next we need to enable the various services.

NOTE: Please note that all software has been pre-installed and configured.  These steps are provided as reference material.

If for some reason the webconsole is not enabled, please visit that unit for instructions on installing and configuring webconsole.

To enable the necessary services for this unit:

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*systemctl enable --now libvirtd*
----

NOTE: The "enable --now" syntax is new in RHEL 8.  It allows for permanently enabling as well as immediately starting services in a single command.

Finally check the service status.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*systemctl status libvirtd*
----

=== Verify Virtualization Host Status

One simple command checks various hardware and software configurations for support of virtualization.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*virt-host-validate*
----

[source,options="nowrap",subs="{markup-in-source}"]
----
  QEMU: Checking for hardware virtualization                                 : PASS
  QEMU: Checking if device /dev/kvm exists                                   : PASS
  QEMU: Checking if device /dev/kvm is accessible                            : PASS
  QEMU: Checking if device /dev/vhost-net exists                             : PASS
  QEMU: Checking if device /dev/net/tun exists                               : PASS
  QEMU: Checking for cgroup 'cpu' controller support                         : PASS
  QEMU: Checking for cgroup 'cpuacct' controller support                     : PASS
  QEMU: Checking for cgroup 'cpuset' controller support                      : PASS
  QEMU: Checking for cgroup 'memory' controller support                      : PASS
  QEMU: Checking for cgroup 'devices' controller support                     : PASS
  QEMU: Checking for cgroup 'blkio' controller support                       : PASS
  QEMU: Checking for device assignment IOMMU support                         : WARN (No ACPI IVRS table found, IOMMU either disabled in BIOS or not supported by this hardware platform)
----

== Deploy A Virtual-Machine with 'virt-install'

Red Hat provides pre-made generic images of RHEL for use as virtual machines in a QCOW2 format.

However, in order to access them for download one needs to have an active Red Hat Enterprise Linux entitlement.  An alternative to downloading a qcow image is to make one.  

Fortunately, that's precisely what you did in the previous unit with Image Builder.

=== Retrieve a QCOW Image

First we need to grab a copy of the image and put it in the right place for our platform.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*cd /var/lib/libvirt/images*
----

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*composer-cli compose image 812019dd-20e5-4528-a99b-09fbe47ca2d8*
----

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*mv *.qcow2 vmguest.qcow2*
----

=== Modify the QCOW Image

Now you need to set a root password in the image

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*virt-customize -a vmguest.qcow2 --root-password password:redhat --uninstall cloud-init*
----

=== Deploy the QCOW Image

Finally it's time to launch the VM

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*virt-install \
   --import \
   --name vmguest \
   --memory 2048 \
   --vcpus 1 \
   --disk /var/lib/libvirt/images/vmguest.qcow2 \
   --graphics vnc \
   --noautoconsole\
   --os-variant rhel8.1*
----

=== Additional CLI Commands

Some additional simple virtual machine management commands

  * *virsh list* lists running virtual machines
  * *virsh list --all* lists all virtual machines regardless of state
  * *virsh start <vm-name>* starts a virtual machine named 
  * *virsh shutdown <vm-name>* performs a soft shutdown of the virtual machine
  * *virsh destroy <vm-name>* performs distructive cold stop the virtual machine

== Explore VM Management with 'Web-Console'

From the menu, select the Machines tab.  You will notice that the interface is still pretty rudimentary when compared the Red Hat Virtualization Manager (RHVM) , but one critical feature is available: the console!

Take some time to explore the capabilities of the Web-Console Machines webui.

Log in to your client (user:root password:redhat) and poke around.  The VM is on a private network and not accessbile from the internet.  You will only be able to access from the webconsole.

== Shutdown Virtual Machines

WARN: It is IMPORTANT to stop or delete the deployed VMs

Using either the CLI (or the Web-Console), be sure to shutdown the VM(s) you deployed to ensure additional workshop exercises perform reasonably.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*virsh list --all*
----

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*virsh shutdown vmguest*
----

== Additional Resources

Cockpit Project Page

    * link:http://cockpit-project.org/blog/category/release.html[Cockpit Project]

Network Related Topics

    * link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/networking_guide/ch-configure_network_bridging[Configure Network Bridging]

    * link:http://blog.leifmadsen.com/blog/2016/12/01/create-network-bridge-with-nmcli-for-libvirt/[Create Network Bridge with nmcli]

[discrete]
== End of Unit

ifdef::env-github[]
link:../RHEL8-Workshop.adoc#toc[Return to TOC]
endif::[]

////
Always end files with a blank line to avoid include problems.
////
