:sectnums:
:sectnumlevels: 3
:imagesdir: ./_images

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:toc:
:toclevels: 1

= Virtualization Management

NOTE: If you are using the web-console and do not see "Virtual Machines" in the menu, chances are that you need to sign-out and sign-in again.

Provided your hardware is reasonably modern, chances are that it supports virtualization.  This unit introduces simple virtualization management using kvm and libvirt.  You will learn how to:

    * Install additional necessary software
    * Enable necessary system services and firewall ports
    * Use the command line to create and manage a virtual machine
    * Use the web console (cockpit) to create and manage a virtual machine

== Getting Started

Starting on the host *workstation*, just make sure you're the root user.  All exercises will be performed on the *workstation* host.

.[root@workstation]#
----
id

uid=0(root) gid=0(root) groups=0(root)
----

Verify that you are on the right host for these exercises.

.[root@workstation ~]#
----
cheat-virt-checkhost.sh
----

You are now ready to proceed with these exercises.

=== Requirements

First we need to ensure the system being used supports either:

    * Intel VT-x and Intel 64 virtualization extensions
    * AMD-V and the AMD64 virtualization extensions

This is done with the following simple commands.

You can start by examining the CPU flags (capabilities) advertised by your system.

.[root@workstation]#
----
grep -E 'svm|vmx' /proc/cpuinfo
----

You are looking for either the Intel flag (vtx) or the AMD flag (svm).  A more sophisticated command makes it a little easier to determine.

.[root@workstation]#
----
if grep -qE 'svm|vmx' /proc/cpuinfo ; then echo "Virt Supported" ; else echo "*WARN* Virt NOT Supported"; fi
----

After you install all the required software, there are some additional tools to provide more detailed reporting on system capabilities.

=== Installation

NOTE: Please note that all software has been pre-installed and configured.  These steps are provided as reference material.

System needs to be configure with access to the following repos:

  * rhel-8-baseos-rpms
  * rhel-8-appstream-rpms

.[root@workstation]#
----
yum install -y qemu-kvm libvirt virt-install libvirt-client libguestfs-tools cockpit-machines lorax-composer composer-cli cockpit-composer
----

=== Enable System Services

NOTE: Please note that all software has been pre-installed and configured.  These steps are provided as reference material.

If for some reason the webconsole is not enabled, please visit that unit for instructions on installing and configuring webconsole.

To enable the necessary services for this unit:

.[root@workstation]#
----
systemctl enable lorax-composer.socket libvirtd
systemctl start lorax-composer libvirtd
----

=== Verify Virtualization Host Status

One simple command checks various hardware and software configurations for support of virtualization.

.[root@workstation]#
----
virt-host-validate
----

----
  QEMU: Checking for hardware virtualization                                 : PASS
  QEMU: Checking if device /dev/kvm exists                                   : PASS
  QEMU: Checking if device /dev/kvm is accessible                            : PASS
  QEMU: Checking if device /dev/vhost-net exists                             : PASS
  QEMU: Checking if device /dev/net/tun exists                               : PASS
  QEMU: Checking for cgroup 'cpu' controller support                         : PASS
  QEMU: Checking for cgroup 'cpuacct' controller support                     : PASS
  QEMU: Checking for cgroup 'cpuset' controller support                      : PASS
  QEMU: Checking for cgroup 'memory' controller support                      : PASS
  QEMU: Checking for cgroup 'devices' controller support                     : PASS
  QEMU: Checking for cgroup 'blkio' controller support                       : PASS
  QEMU: Checking for device assignment IOMMU support                         : WARN (No ACPI IVRS table found, IOMMU either disabled in BIOS or not supported by this hardware platform)
----

== Image Builder

=== Overview

Red Hat provides pre-crated images of RHEL for use as virtual machines.  This come in a QCOW format.  However, in order to access them for download one needs to have an active Red Hat Enterprise Linux entitlement.  One alternative is to simply build a fresh image using the `Image Builder`.

`Image Builder` is a set of tools to create custom RHEL images in a variety of formats for compatibility with major cloud providers and virtualization technologies available.  We are only going to leverage an existing blueprint, but note that they are easy to extend and customize for your unique requirements.

=== List Blueprints

----
composer-cli blueprints list
----

----
example-atlas
example-development
example-http-server
----

=== Compose a Blueprint

We are going to leverage the `example-http-server` for our purposes.

----
composer-cli compose start example-http-server qcow2
----

----
Compose 812019dd-20e5-4528-a99b-09fbe47ca2d8 added to the queue
----






WARNING: I'M STUCK HERE, THE BUILD IS HUNG



== Deploy A Virtual-Machine with 'virt-install'

Now you are ready to leverage the example-http-server and deploy the VM with Red Hat Enterprise Linux.

=== Retrieve a QCOW Image

First we need to grab a copy of the image

----
cd /var/lib/libvirt/images

wget -O rhel-8.1-x86_64-kvm.qcow2 http://core.example.com/images/rhel-8.1-x86_64-kvm.qcow2
----

=== Modify the QCOW Image

Now you need to set a root password in the image

----
virt-customize -a rhel-8.1-x86_64-kvm.qcow2 --root-password password:redhat --uninstall cloud-init
----

=== Deploy the QCOW Image

Finally it's time to launch the VM

----
virt-install \
  --import \
  --name vmguest-01 \
  --memory 2048 \
  --vcpus 1 \
  --disk /var/lib/libvirt/images/rhel-8.1-x86_64-kvm.qcow2 \
  --graphics vnc \
  --noautoconsole\
  --os-variant rhel8.1
----

INFO: If you hop on the Virtual Machines Manager in the Web-Console, you an bring up the VM's Console and watch the deployment.

=== Additional CLI Commands

Some additional simple virtual machine management commands

----
virsh list
virsh list --all

virsh start vmguest-01
virsh shutdown vmguest-01
----

== Explore VM Management with 'Web-Console'

From th menu, select the Machines tab.  You will notice that the interface is still pretty rudimentary, but one critical feature is available: the console!

Take some time to explore the capabilities of the Web-Console Machines webui.

== Shutdown Virtual Machines

WARN: It is IMPORTANT to stop or delete the deployed VMs

Using either the CLI (or the Web-Console), be sure to shutdown the VM(s) you deployed to ensure additional workshop exercises perform reasonably.

----
virsh list --all

virsh shutdown vmguest-01
----

== Additional Resources

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/networking_guide/ch-configure_network_bridging

http://blog.leifmadsen.com/blog/2016/12/01/create-network-bridge-with-nmcli-for-libvirt/

Cockpit Project Page

    * link:http://cockpit-project.org/blog/category/release.html[Cockpit Project]

[discrete]
== End of Unit

link:../RHEL8-Workshop.adoc#toc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
