:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Wayland

Wayland was first introduced to the Fedora community back in version 25. For several years, development, hardening and rich features have made Wayland the new standard in graphical desktop environments. (replacing X.org)

A detailed explanation of the architecture, functionality and features can be found at https://en.wikipedia.org/wiki/Wayland_(display_server_protocol) or you can simply go to the project’s homepage:  https://wayland.freedesktop.org/ for more details...

== Installation

The graphical desktop is installed by default in a "workstation" install but this is not the case in a "server" installation.

In the event you installed a text based RHEL host, you can load and enable Wayland with the following steps:

----
yum groupinstall Workstation

systemctl set-default graphical

reboot
----

For today’s lab this has already been done for you...


Log into the console of your workstation as student.
  





Click on Activities, then type in the search box.  “firewall”


  



Click on “Firewall”
This will bring up the Gnome Software package installation GUI…
  



Click on “Firewall”.
Then click “Install”
  

  







Click “Launch”...
You’ll be prompted for the password for student - enter the password.
   
Feel free to browse the interface but don’t make any changes…
When you are done exploring - click on the “x” in the upper right hand corner.




Now lets configure your desktop to have a menu system…
Click on “Activities” then click on the Gnome Terminal icon...
  





Become root.


$  sudo -i


Then we’ll install some packages to better configure our desktop experience…


# yum install -y gnome-tweaks


  



CLose the terminal window. Click on the “Activities” button… then type “tweaks” in the search window.
  



Click on the Tweaks icon right below the search box.
  

On the left hand side menu, click Extensions, then turn on the Applications Menu…
  

Now click on Windows, then activate the Maximixe and Minimize buttons for all windows…
  

Close the the Tweaks interface by clicking on the X in the upper right hand corner…
Now you have an Applications menu system in Gnome!
  

Take a tour of the menus… Click on Utilities → Disks…
  

Note - now all graphical apps have a maximize and minimize button…
Close the app without making changes…




















== Additional Resources

Red Hat Documentation

    * link:https://https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8-beta/html/installing_identity_management_and_access_control/deploying-session-recording[Deplying Session Recording on Red Hat Enterprise Linux]

[discrete]
== End of Unit

link:../RHEL8-Workshop.adoc#toc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////

