= New Container Tools

== Podman

With Podman, you can: find, run, build, and share containers.

[root@workstation]
----
ssh node3.example.com
----

[root@node3]
----
yum install -y podman
----

[root@node3]
----
podman pull httpd
podman images
podman run -p 80:80 -d httpd
----


== Buildah

== Skopeo








Working notes leading towards a lab:

yum install podman -y


Grab s2i and build a 

podman pull httpd
podman images
podman run -p 80:80 -d httpd

on workstation:

node1.example.com

It Works!

To pull registry.redhat.io/rhscl/httpd-24-rhel7 requires access.redhat.com creds

podman run -p 80:8080 -d rhscl/httpd-24-rhel7

rhel test page.

skopeo inspect containers-storage:docker.io/library/httpd:latest
{
    "Name": "docker.io/library/httpd",
    "Digest": "sha256:d93278029af342292a3af350bfb3d89edbe064f1d5c82f6841cb6abf79902875",
    "RepoTags": [],
    "Created": "2019-03-05T06:02:44.070979505Z",
    "DockerVersion": "18.06.1-ce",
    "Labels": null,
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:f7e2b70d04ae3f516c08c24d88de0f82699aaf3ee98af6eb208bd234136142b4",
        "sha256:84006542c6886808e4a237c4c382d5b3b471c8c10415e4b997f218acda71a306",
        "sha256:dae6fe3c5e81fce55ed1b582bd9fe2cd0c8ffd8a1ef56e4aba49526c9a7ebd9f",
        "sha256:33fc493aff90095281a8938d001dbe01c988c5765a392d2a4b52c84cff0b62f0",
        "sha256:9a4113020573f9f9d5b288ee3c768131f42bcd48b734d2ab44a5eba3b06d6e22"
    ]
}


/usr/local/apache2/htdocs/


buildah from docker.io/library/httpd
buildah copy httpd-working-container ./index.html /usr/local/apache2/htdocs/
buildah commit httpd-working-container httpd-wedidit
podman run -p 81:80 -d httpd-wedidit
[root@node1 ~]# curl localhost:81
<html><h1>You know it!</h1></html>

[root@node1 ~]# podman images
REPOSITORY                                TAG      IMAGE ID       CREATED          SIZE
localhost/httpd-wedidit                   latest   ec02e6c550b1   44 seconds ago   137 MB
docker.io/library/httpd                   latest   2d1e5208483c   10 days ago      137 MB
registry.redhat.io/rhscl/httpd-24-rhel7   latest   510d1c5f05f9   7 weeks ago      323 MB


do it from dockerfile to see if it's bigger.
