---
- hosts: node3
  tasks:

    - name: "SETUP PODMAN: yum install podman,net-tools,wget"
      yum: name=podman,net-tools,wget state=installed
      register: result
      retries: 10
      until: result is succeeded
      delay: 5

    - name: "SETUP PODMAN: config file installs"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - {src: 'podman-registries.j2', dest: '/etc/containers/registries.conf'}
        - {src: 'podman-ocifile.j2',    dest: '/root/custom_image.OCIFile'}

    - name: "SETUP PODMAN: cheat script installs"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0744
      with_items:
        - {src: 'cheat-checkhost.j2', dest: '/usr/local/bin/cheat-podman-checkhost.sh'}
        - {src: 'cheat-podman-loadregistry.j2', dest: '/usr/local/bin/cheat-podman-loadregistry.sh'}
