---
- hosts: workstation
  tasks:

    - name: "SETUP VIRTUALIZATION: yum install qemu-kvm libvirt virt-install libvirt-client libguestfs-tools"
      yum: name=qemu-kvm,libvirt,firewalld,virt-install,libvirt-client,libguestfs-tools,wget,cockpit-machines,lorax-composer,composer-cli,cockpit-composer state=installed
      register: result
      retries: 10
      until: result is succeeded
      delay: 5

    - name: "SETUP VIRTUALIZATION: cockpit service restart"
      service: name="cockpit.socket" enabled=yes

    - name: "SETUP VIRTUALIZATION: imagebuilder service restart"
      service: name="cockpit" state=started enabled=yes

    - name: "SETUP VIRTUALIZATION: imagebuilder service restart"
      service: name="libvirtd" state=started enabled=yes

    - name: "SETUP VIRTUALIZATION: imagebuilder service restart"
      service: name="lorax-composer" state=started enabled=yes

    - name: "SETUP VIRTUALIZATION: firewalld service start"
      service: name="firewalld" state=started enabled=yes

    - name: "SETUP VIRTUALIZATION: cheat script installs"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0744
      with_items:
        - {src: 'cheat-checkhost.j2',           dest: '/usr/local/bin/cheat-virt-checkhost.sh'}

