---
- hosts: node1
  tasks:
  
    - name: "rhel8-unit-firewalld : yum install firewalld"
      yum: name=firewalld state=installed
      register: result
      retries: 10
      until: result is succeeded
      delay: 5

    - name: "rhel8-unit-firewalld : service stop nftables"
      service: name=nftables state=stopped enabled=no

    - name: "rhel8-unit-firewalld : service start firewalld"
      service: name=firewalld state=started enabled=yes
      
    - name: "rhel8-unit-firewalld : cheat script installs"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0744
      with_items:
        - {src: 'cheat-checkhost.j2',               dest: '/usr/local/bin/cheat-firewalld-checkhost.sh'}
        - {src: 'cheat-firewalld-customconfigs.j2', dest: '/usr/local/bin/cheat-firewalld-customconfigs.sh'}

