:gitrepo: https://github.com/xtophd/RHEL8-Workshop
:includedir: _include
:doctype: book
:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:imagesdir: ./_include/_images/

= The Definitive Red Hat Enterprise Linux 8 Hands-on Lab

[discrete]
== Presented By

  * Christoph Doerbeck
  * Karl Abbott
  * Eddie Chen
  * Gordon Keegan
  * Matt St. Onge
  
[discrete]
== Introduction

First of all, THANK YOU for registering and participating in *The Definitive Red Hat Enterprise Linux 8 Hands-on Lab*.  The lab team has worked very hard to assemble a series of exercises to introduce many of the new features and capabilities found in the next great release of RHEL.  We hope you enjoy this experience and please don't hesitate to ask questions.

Also, please don't forget to review this session at the completion of this lab.  Your reviews and feedback help keep labs like these as top attractions for the Red Hat Summit.

NOTE:  This whole effort is done using official Red Hat software and although things can likely be set up to work with upstream software components (Fedora, CentOS, etc...), alternate derivatives of RHEL are not tested or validated with these exercises.

[discrete]
== Workshop Abstract

. link:{includedir}/abstract.adoc[About This Workshop]

[discrete]
== Conventions Used

This guide is intended to support a series of workshop exercises for individuals getting familiar with Red Hat Enterprise Linux 8.  What follows are examples of how this document is formatted and expected to be consumed.

[discrete]
=== Tips, Notes & Warnings

TIP: Extra info which could be helpful, but not essential for a given task or discussion

NOTE: Special information to pay attention

WARNING: Critical information which could help you avoid major set backs

[discrete]
=== Executing tasks on the CLI

[discrete]
==== Input

Each block of commands to execute will be labeled with the expected *user-id* and *host*.  To enhance cut & paste efficiency, the command prompt is omitted from each line.

.[root@master ~]#
----
systemctl status sshd
----

[discrete]
==== Output

Sample output will be titled with _'Your output should look like this'_ (or _'Command Output'_) and also be indented to help with visual identification.  Sometimes there will also be footnotes and/or callouts.

.Command Output
[source,indent=4]
----
● sshd.service - OpenSSH server daemon
   Loaded: loaded (/usr/lib/systemd/system/sshd.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-02-26 12:04:16 EST; 27min ago // <1>
     Docs: man:sshd(8)
           man:sshd_config(5)
 Main PID: 3094 (sshd)
   CGroup: /system.slice/sshd.service
           └─3094 /usr/sbin/sshd -D
...<snip>...
----
<1> This is the line we are interested in with a special note

[discrete]
==== Alternate Commands

The workshop often provides cheat-scripts to ease certain complex tasks.  This helps the class stay focused and reduces the likelihood of errors and disruptions to the workshop delivery.  Honestly, we are not here to learn `vi`, `emacs` or start debates about the merits of `sed` and `awk`.

The native commands which the cheat-scripts utilize will be documented in the following way.

.[root@master ~]#
----
cheat-service-status.sh
----

[NOTE]
====
_Native command(s) to verify system service_
----
systemctl status sshd
----
====



[discrete]
== How to Connect

There are three options to complete the lab.

  . Follow the instructions to download the ssh-key and use a local terminal for the majority of exercises
  . Skip downloading the ssh-key and simply use a local terminal with credentials provided by your instructors
  . The last bullet of the LAB INFORMATION page, provides a link 'to consoles'.  By clicking that link, you can get true console access to "0WORKSTATION".  

NOTE: you will need true console (GUI) on "0WORKSTATION" for the *Wayland* and *Web Console* units.



[discrete]
== Quick Overview of *tmux*

NOTE: We strongly advise the use of *tmux* before you begin your exercises.  This will prevent the loss of active work in the event your connection is broken.  

Simple list of *tmux* commands:

  * run tmux: `tmux`
  * create an additional terminal shell: `ctrl-b c`
  * switch to Next terminal shell: `ctrl-b n`
  * switch to Previous terminal shell: `ctrl-b p`

After a broken connection:

  * list available sessions : `tmux ls`
  * attach to disconnected session : `tmux a [-t #]`



[discrete]
== How to Cut & Paste with Web Console

NOTE: Chrome is the only "supported" browser that I test for this workshop.  Chances are you will have the same experience with Firefox, but that is not confirmed.

For Linux or MacOS based desktops:

  * normal mouse selections with cut & paste should work as expected.

For Windows desktops:

  * COPY standard app: CTRL-c
  * PASTE to stardard app: CTRL-v
  * COPY from web-console terminal: CTRL-a + CTRL-c
  * PASTE to web-console terminal: CTRL-a + CTRL-v



[discrete]
== RHEL 8 LAB: EXERCISES

[#toc]
  . link:{includedir}/getting-started.adoc[*Workshop Preparation* - DO THIS FIRST! ] _(workstation)_
  . link:{includedir}/webconsole.adoc[*Web Console* - (UPDATED) System Management] _(workstation, node2)_
  . link:{includedir}/systemd.adoc[*SystemD* - (UPDATED) System Service Management] _(node1)_
  . link:{includedir}/firewalld.adoc[*FirewallD* - (UPDATED) Firewall Service Management] _(node1)_
  . link:{includedir}/nftables.adoc[*NFTables* - (NEW) Firewall Subsystem] _(node2)_
  . link:{includedir}/ebpf.adoc[*eBPF Tracing* - (NEW) Extended Berkeley Packet Filter for Linux Kernel Tracing] _(node2)_
  . link:{includedir}/appstream-yum.adoc[*App Stream* - (NEW) Application Delivery] _(node1, node2, node3)_
  . link:{includedir}/podman.adoc[*Podman* - (NEW) Container Management] _(node3)_
  . link:{includedir}/buildah.adoc[*Buildah & Skopeo* - (NEW) Container Development] _(node3)_
  . link:{includedir}/virtualization.adoc[*Virtualizaion* - (NEW) Virtualization Management] _(workstation)_
  . link:{includedir}/tlog.adoc[*TLog* - (NEW) Session Logging] _(node1)_
  . link:{includedir}/stratis.adoc[*Stratis* - (NEW) Storage Management] _(node2)_
  . link:{includedir}/boom.adoc[*BOOM* - (NEW) Boot Management] _(node3)_
  . link:{includedir}/wayland.adoc[*Wayland* - (NEW) Desktop GUI ] _(workstation)_


////  
TO PRINT THIS DOC REMOVE THIS LINE AND COMMENTS AROUND INCLUDES
include::{includedir}/Getting-Started.adoc[leveloffset=+1]
include::{includedir}/webconsole.adoc[leveloffset=+1]
include::{includedir}/systemd.adoc[leveloffset=+1]
include::{includedir}/firewalld.adoc[leveloffset=+1]
include::{includedir}/nftables.adoc[leveloffset=+1]
include::{includedir}/appstream-yum.adoc[leveloffset=+1]
include::{includedir}/podman.adoc[leveloffset=+1]
include::{includedir}/buildah[leveloffset=+1]
include::{includedir}/tlog.adoc[leveloffset=+1]
include::{includedir}/stratis.adoc[leveloffset=+1]
include::{includedir}/boom.adoc[leveloffset=+1]
include::{includedir}/wayland.adoc[leveloffset=+1]
////

[discrete]
== The End

Please remember to fill out the survey.  The RHEL 8 Lab team really appreciates your time spent with us today and we hope you enjoy the rest of your Summit experience.

.Built-in
asciidoctor-version:: {asciidoctor-version}
safe-mode-name:: {safe-mode-name}

////
Always end files with a blank line to avoid include problems.
////
